import {notFound} from 'next/navigation';
import {findPhoto,origin,commerceStatus,db} from '@/lib/server';
import {demoPhotos} from '@/lib/content';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {PhotoActions} from '@/components/photo-actions';
export const dynamic='force-dynamic';
async function photo(slug:string){return demoPhotos.find(p=>p.slug===slug)||await findPhoto(slug)}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=await photo(slug);if(!p)return {title:'Photograph not found',robots:{index:false,follow:false}};return {title:p.title,description:p.caption.slice(0,160),alternates:{canonical:origin()+'/journal/'+p.slug},robots:p.demo?{index:false,follow:true}:undefined,openGraph:{title:p.title,description:p.caption.slice(0,160),type:'article',url:origin()+'/journal/'+p.slug}}}
export default async function PhotoPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=await photo(slug);if(!p)notFound();const user=await getChatGPTUser();let ownedOrder:string|undefined,saved=false;if(user&&!p.demo){const o=await db().prepare("SELECT id FROM orders WHERE user_id=? AND photo_id=? AND status='paid'").bind(user.userId,p.id).first<{id:string}>();ownedOrder=o?.id;saved=!!await db().prepare('SELECT id FROM bookmarks WHERE user_id=? AND photo_id=?').bind(user.userId,p.id).first()}
const structured={'@context':'https://schema.org','@type':'ImageObject',name:p.title,description:p.caption,contentUrl:new URL(p.preview,origin()).href,creator:{'@type':'Person',name:p.demo?p.credit:'Sina Afshar'},copyrightNotice:p.demo?'AI-generated sample image':'© Sina Afshar',license:origin()+'/legal/license'};
return <main id="main" className="page content-page"><p style={{paddingTop:30}}><a href="/" className="text-link">← Back to the journal</a></p><div className="detail-layout"><div><div className="detail-image"><img src={p.preview} alt={p.alt} width={p.width} height={p.height} fetchPriority="high"/></div><p className="image-credit">{p.demo?<>AI-generated sample image · Not a photograph by Sina · Not for sale</>:<>© Sina Afshar · Web preview. Purchased originals are delivered privately.</>}</p></div><article className="detail-story"><p className="eyebrow">{p.category} / {p.location||'Field notes'}</p><h1>{p.title}</h1><p className="caption">{p.caption}</p><dl>{p.camera&&<div><dt>Camera</dt><dd>{p.camera}</dd></div>}{p.lens&&<div><dt>Lens</dt><dd>{p.lens}</dd></div>}{p.settings&&<div><dt>Settings</dt><dd>{p.settings}</dd></div>}{!p.demo&&<div><dt>Published</dt><dd>{new Date(p.created_at).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</dd></div>}</dl><PhotoActions photo={p} signedIn={!!user} canBuy={commerceStatus().enabled} ownedOrder={ownedOrder} initialSaved={saved}/></article></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\\u003c')}}/></main>}
