import test from 'node:test';
import assert from 'node:assert/strict';
import {photoPresets,neutral,renderPhotoPixels,parseRecipe,type EditRecipe} from '../lib/photo-filters.ts';
import {csvText} from '../lib/studio-model.ts';
const width=32,height=20;
const pixels=new Uint8ClampedArray(width*height*4);
for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;pixels.set([x*8,y*12,(x*17+y*7)%256,(x+y)%11===0?0:255],i)}
const recipe=(presetId='original',strength=100):EditRecipe=>({version:1,presetId,strength,adjustments:{...neutral}});
test('24 presets make 24 distinct pixel transformations without altering input or alpha',()=>{assert.equal(photoPresets.length,24);assert.equal(new Set(photoPresets.map(p=>p.id)).size,24);const before=pixels.slice(),signatures=new Set<string>();for(const p of photoPresets){const output=renderPhotoPixels(pixels,width,height,recipe(p.id));assert.notDeepEqual(output,pixels,p.id);for(let i=3;i<pixels.length;i+=4)assert.equal(output[i],pixels[i],p.id);signatures.add(Buffer.from(output).toString('base64'))}assert.equal(signatures.size,24);assert.deepEqual(pixels,before)});
test('reset and zero preset strength reproduce source bytes exactly',()=>{assert.deepEqual(renderPhotoPixels(pixels,width,height,recipe()),pixels);for(const p of photoPresets)assert.deepEqual(renderPhotoPixels(pixels,width,height,recipe(p.id,0)),pixels,p.id)});
test('tile exports match a whole-image render, including grain and vignette',()=>{const r=recipe('chrome');r.adjustments.noise=30;r.adjustments.sharpness=25;r.adjustments.vignette=20;const full=renderPhotoPixels(pixels,width,height,r),tiled=new Uint8ClampedArray(pixels.length);for(let y=0;y<height;y+=6){const rows=Math.min(6,height-y),top=y?1:0,bottom=y+rows<height?1:0;const source=pixels.slice((y-top)*width*4,(y+rows+bottom)*width*4),out=renderPhotoPixels(source,width,rows+top+bottom,r,y-top,height);tiled.set(out.slice(top*width*4,(top+rows)*width*4),y*width*4)}assert.deepEqual(tiled,full);assert.deepEqual(renderPhotoPixels(pixels,width,height,r),full)});
test('exposure brightens midtones and silver conversion removes colour',()=>{const p=new Uint8ClampedArray([80,100,120,255]);const r=recipe();r.adjustments.exposure=1;const out=renderPhotoPixels(p,1,1,r);assert.ok(out[0]>p[0]&&out[1]>p[1]&&out[2]>p[2]);const mono=renderPhotoPixels(p,1,1,recipe('silver'));assert.equal(mono[0],mono[1]);assert.equal(mono[1],mono[2])});
test('smoothing reduces small pixel noise in a flat field',()=>{const p=new Uint8ClampedArray(20*20*4);for(let i=0;i<p.length;i+=4){const v=(Math.floor(i/4/20)+i/4)%2?105:95;p.set([v,v,v,255],i)}const r=recipe();r.adjustments.noise=100;const out=renderPhotoPixels(p,20,20,r);const energy=(a:Uint8ClampedArray)=>a.reduce((s,v,i)=>i%4===3?s:s+(v-100)**2,0);assert.ok(energy(out)<energy(p))});
test('imported edit recipes reject unknown presets and unsafe or invalid settings',()=>{assert.deepEqual(parseRecipe(recipe('clean')),recipe('clean'));for(const bad of [{...recipe(),version:2},{...recipe(),presetId:'not-a-filter'},{...recipe(),strength:NaN},{...recipe(),adjustments:{...neutral,exposure:20}},{...recipe(),adjustments:{}}])assert.throws(()=>parseRecipe(bad))});
test('sales CSV preserves quoted text and neutralizes spreadsheet formulas',()=>{const text=csvText([['=HYPERLINK("https://bad")',' +SUM(A1)','Normal, title','line\nbreak']]);assert.ok(text.startsWith('"\'=HYPERLINK(""https://bad"")"'));assert.ok(text.includes('"\' +SUM(A1)"'));assert.ok(text.includes('"Normal, title"'));assert.ok(text.includes('"line\nbreak"'))});
