import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {Miniflare,Log,LogLevel}=createRequire(require.resolve('wrangler/package.json'))('miniflare');
const base='https://sina-photo-journal.afsharsn.chatgpt.site';
const moduleFiles=(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')||p.endsWith('.mjs'));
const modules=[{type:'ESModule',path:resolve('dist/server/index.js')},...moduleFiles.filter(p=>p!=='index.js').map(p=>({type:'ESModule',path:resolve('dist/server',p)}))];
const mf=new Miniflare({modules,modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{SITE_URL:base,OWNER_USER_ID:'test-owner',COMMERCE_ENABLED:'false'},assets:{directory:resolve('dist/client'),routerConfig:{has_user_worker:true}},log:new Log(LogLevel.ERROR)});
let checks=0;
const headers=(user='buyer-a',sameOrigin=true)=>({'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test',Origin:sameOrigin?base:'https://attacker.example','Content-Type':'application/json'});
async function req(path,options={}){if(options.body instanceof FormData){const encoded=new Request(base+path,options);options={...options,headers:encoded.headers,body:new Uint8Array(await encoded.arrayBuffer())}}return mf.dispatchFetch(base+path,options)}
async function check(label,fn){await fn();checks++;console.log('PASS '+label)}
try{
const db=await mf.getD1Database('DB');
for(const name of (await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort()){const sql=await readFile('drizzle/'+name,'utf8');for(const statement of sql.split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(statement).run()}
await check('public journal renders with local sample images',async()=>{const r=await req('/');assert.equal(r.status,200);const h=await r.text();assert.match(h,/Look a little/);assert.match(h,/AI-generated/);assert.match(h,/images\/alpine.jpg/);assert.ok(!h.includes('no such table'))});
await check('production HTML references available browser assets',async()=>{const html=await(await req('/')).text();const sources=[...html.matchAll(/(?:src|href)="([^" ]+\.(?:js|css))"/g)].map(m=>m[1]);assert.ok(sources.length>0);for(const source of sources){const asset=await req(source);assert.equal(asset.status,200,source);assert.match(asset.headers.get('content-type'),source.endsWith('.js')?/javascript/:/css/,source)}console.log('Asset references checked:',sources.length)});
await check('every public homepage link opens a complete HTML page',async()=>{
  const html=await(await req('/')).text();
  const paths=[...new Set([...html.matchAll(/<a\b[^>]*href="([^"#]+)"/g)].map(m=>m[1]).filter(p=>p.startsWith('/')))];
  assert.ok(paths.includes('/lab')&&paths.includes('/account')&&paths.includes('/custom-orders'));
  for(const path of paths){
    const response=await req(path.replaceAll('&amp;','&'));
    assert.equal(response.status,200,path);
    assert.match(response.headers.get('content-type'),/text\/html/,path);
    const body=await response.text();
    assert.match(body,/<main\b/,path);
    assert.ok(!body.includes('The page could not be loaded.'),path);
  }
  console.log('Homepage destinations checked:',paths.length);
});
await check('Photo Lab renders and metadata is present',async()=>{const r=await req('/lab');assert.equal(r.status,200);const h=await r.text();assert.match(h,/The Photo/);assert.match(h,/canonical/);assert.match(h,/Daylight portrait/)});
await check('SEO endpoints respond with actual routes',async()=>{const robots=await req('/robots.txt');assert.equal(robots.status,200);assert.match(await robots.text(),/sitemap.xml/);const sitemap=await req('/sitemap.xml');assert.equal(sitemap.status,200);assert.match(await sitemap.text(),/\/lab/);assert.equal((await req('/does-not-exist')).status,404)});
await check('anonymous users cannot access account data or studio APIs',async()=>{assert.equal((await req('/api/presets')).status,401);assert.equal((await req('/api/studio/photos')).status,401);assert.equal((await req('/api/account/export')).status,401)});
await check('collectors cannot publish photographs',async()=>{assert.equal((await req('/api/studio/photos',{headers:headers()})).status,403)});
await check('cross-origin mutation fails before writing',async()=>{const r=await req('/api/account',{method:'POST',headers:headers('buyer-a',false),body:JSON.stringify({accept:true})});assert.equal(r.status,403)});
await check('account requires consent and accepts a valid registration',async()=>{assert.equal((await req('/api/account',{method:'POST',headers:headers(),body:'{"accept":false}'})).status,400);assert.equal((await req('/api/account',{method:'POST',headers:headers(),body:'{"accept":true}'})).status,200)});
let presetId;
const setup={name:'Portrait',data:{scenarioId:'portrait-daylight',gear:{cameraName:'Camera',lensName:'Lens',sensor:'full-frame',focalLength:85,maxAperture:1.8,stabilizationStops:0,hasTripod:false,flashAvailable:false},context:{light:'bright',motion:'slow',intent:'balanced',handheld:true,flashAllowed:true,output:'standard'}}};
await check('saved setups persist and are isolated by user',async()=>{const r=await req('/api/presets',{method:'POST',headers:headers(),body:JSON.stringify(setup)});assert.equal(r.status,201);presetId=(await r.json()).id;assert.equal((await(await req('/api/presets',{headers:headers('buyer-b')})).json()).presets.length,0);assert.equal((await(await req('/api/presets',{headers:headers()})).json()).presets.length,1);await req('/api/presets',{method:'DELETE',headers:headers('buyer-b'),body:JSON.stringify({id:presetId})});assert.equal((await(await req('/api/presets',{headers:headers()})).json()).presets.length,1)});
const bytes=await readFile('public/images/alpine.jpg');let photoId;
await check('owner upload creates durable draft with private original',async()=>{const data=new FormData();data.set('original',new Blob([bytes],{type:'image/jpeg'}),'original.jpg');data.set('preview',new Blob([bytes],{type:'image/jpeg'}),'preview.jpg');data.set('metadata',JSON.stringify({title:'Test lake',caption:'A private draft.',alt:'A blue lake below mountains',category:'Landscape',price_cents:1500,published:0,width:1536,height:1024,rights:true}));const h=headers('test-owner');delete h['Content-Type'];const r=await req('/api/studio/photos',{method:'POST',headers:h,body:data});if(r.status!==201)console.log(await r.clone().text());assert.equal(r.status,201);photoId=(await r.json()).id;assert.equal((await req('/api/preview/'+photoId)).status,404);assert.equal((await req('/api/preview/'+photoId,{headers:headers('test-owner')})).status,200);const stored=await(await mf.getR2Bucket('BUCKET')).get('originals/'+photoId);assert.equal(stored.size,bytes.length)});
await check('publication exposes only the preview and escaped caption',async()=>{const r=await req('/api/studio/photos',{method:'PATCH',headers:headers('test-owner'),body:JSON.stringify({id:photoId,published:1,caption:'<script>alert("xss")</script>'})});assert.equal(r.status,200);const image=await req('/api/preview/'+photoId);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/jpeg');assert.equal(image.headers.get('x-content-type-options'),'nosniff');const row=await db.prepare('SELECT slug FROM photos WHERE id=?').bind(photoId).first();const detail=await req('/journal/'+row.slug);const html=await detail.text();assert.equal(detail.status,200);assert.ok(!html.includes('<script>alert("xss")</script>'));assert.ok(!html.includes('originals/'+photoId))});
await check('unconfigured checkout refuses all payments',async()=>{const r=await req('/api/checkout',{method:'POST',headers:headers(),body:JSON.stringify({photo_id:photoId,licenseAccepted:true,immediateDelivery:true})});assert.equal(r.status,503)});
const now=new Date().toISOString();const orderId='test-order';
await db.prepare("INSERT INTO orders (id,user_id,photo_id,photo_title,amount,currency,status,created_at,consent_at,terms_version,license_text,seller_snapshot,buyer_email,receipt_sent_at) VALUES (?,?,?,?,?,'eur','paid',?,?,?,?,?,?,?)").bind(orderId,'buyer-a',photoId,'Test lake',1500,now,now,'test','Personal use',JSON.stringify({name:'Test seller',address:'Test',email:'test@example.test',phone:'test',tax_id:'test'}),'buyer-a@example.test',now).run();
await check('database prevents duplicate active purchases',async()=>{await assert.rejects(db.prepare("INSERT INTO orders SELECT 'duplicate-order',user_id,photo_id,photo_title,amount,currency,status,stripe_session_id,payment_intent,created_at,paid_at,consent_at,terms_version,license_text,seller_snapshot,downloaded_at,receipt_sent_at,buyer_email FROM orders WHERE id=?").bind(orderId).run(),/UNIQUE/) });
await check('purchased original downloads only for its buyer',async()=>{assert.equal((await req('/api/download/'+orderId)).status,401);assert.equal((await req('/api/download/'+orderId,{headers:headers('buyer-b')})).status,403);const r=await req('/api/download/'+orderId,{headers:headers()});assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal((await r.arrayBuffer()).byteLength,bytes.length);const o=await db.prepare('SELECT downloaded_at FROM orders WHERE id=?').bind(orderId).first();assert.ok(o.downloaded_at)});
await check('refunded order cannot download the original',async()=>{await db.prepare("UPDATE orders SET status='refunded' WHERE id=?").bind(orderId).run();assert.equal((await req('/api/download/'+orderId,{headers:headers()})).status,403)});
await check('requests cannot target another customer’s order',async()=>{const b=JSON.stringify({type:'withdrawal',message:'I withdraw from this order.',order_id:orderId});assert.equal((await req('/api/requests',{method:'POST',headers:headers('buyer-b'),body:b})).status,404);assert.equal((await req('/api/requests',{method:'POST',headers:headers(),body:b})).status,201)});
let customId,customVersion;
const customBrief={title:'A portrait session',service:'Portrait or photo session',intended_use:'Personal',brief:'Outdoor portraits with soft afternoon light and three final photographs.',location:'Pisa',target_date:'',budget_cents:25000,accept:true};
await check('custom orders are public to discover and authenticated to submit',async()=>{const page=await req('/custom-orders');assert.equal(page.status,200);assert.match(await page.text(),/just for you/);assert.equal((await req('/api/custom-orders',{method:'POST',body:JSON.stringify(customBrief),headers:{Origin:base,'Content-Type':'application/json'}})).status,401);assert.equal((await req('/api/custom-orders',{method:'POST',headers:headers('buyer-a',false),body:JSON.stringify(customBrief)})).status,403)});
await check('custom briefs validate terms and future dates before saving',async()=>{assert.equal((await req('/api/custom-orders',{method:'POST',headers:headers(),body:JSON.stringify({...customBrief,accept:false})})).status,400);assert.equal((await req('/api/custom-orders',{method:'POST',headers:headers(),body:JSON.stringify({...customBrief,target_date:'2020-02-30'})})).status,400);const r=await req('/api/custom-orders',{method:'POST',headers:headers(),body:JSON.stringify(customBrief)});assert.equal(r.status,201);customId=(await r.json()).id});
await check('custom briefs and conversations are private to customer and photographer',async()=>{assert.equal((await(await req('/api/custom-orders',{headers:headers('buyer-b')})).json()).orders.length,0);assert.equal((await req('/api/custom-orders?id='+customId,{headers:headers('buyer-b')})).status,404);const r=await req('/api/custom-orders?id='+customId,{headers:headers('test-owner')});assert.equal(r.status,200);customVersion=(await r.json()).order.updated_at;assert.equal((await req('/api/custom-orders',{method:'PATCH',headers:headers('buyer-b'),body:JSON.stringify({id:customId,action:'message',body:'A forged private reply'})})).status,404)});
await check('only photographer can quote and stale proposals cannot be accepted',async()=>{const proposal={id:customId,updated_at:customVersion,status:'quoted',quote_cents:20000,proposal:'Three edited portraits with personal-use rights, date and final terms to be agreed.'};assert.equal((await req('/api/custom-orders',{method:'PATCH',headers:headers(),body:JSON.stringify(proposal)})).status,403);assert.equal((await req('/api/custom-orders',{method:'PATCH',headers:headers('test-owner'),body:JSON.stringify(proposal)})).status,200);assert.equal((await req('/api/custom-orders',{method:'PATCH',headers:headers(),body:JSON.stringify({id:customId,updated_at:customVersion,action:'interest'})})).status,409);customVersion=(await(await req('/api/custom-orders?id='+customId,{headers:headers()})).json()).order.updated_at;assert.equal((await req('/api/custom-orders',{method:'PATCH',headers:headers(),body:JSON.stringify({id:customId,updated_at:customVersion,action:'interest'})})).status,200)});
await check('private replies record server-selected authors and are included in export',async()=>{for(const user of ['buyer-a','test-owner'])assert.equal((await req('/api/custom-orders',{method:'PATCH',headers:headers(user),body:JSON.stringify({id:customId,action:'message',body:'Let us discuss the available dates.',author_role:'photographer'})})).status,200);const r=await(await req('/api/custom-orders?id='+customId,{headers:headers()})).json();assert.equal(r.messages[0].author_role,'customer');assert.equal(r.messages[1].author_role,'photographer');const exported=await(await req('/api/account/export',{headers:headers()})).json();assert.equal(exported.custom_orders.results.length,1);assert.equal(exported.custom_messages.results.length,2)});
await check('account deletion removes owned profile and presets, retains financial record',async()=>{const r=await req('/api/account',{method:'DELETE',headers:headers(),body:'{"confirm":"DELETE"}'});assert.equal(r.status,200);assert.equal(await db.prepare('SELECT user_id FROM profiles WHERE user_id=?').bind('buyer-a').first(),null);assert.equal(await db.prepare('SELECT id FROM presets WHERE id=?').bind(presetId).first(),null);assert.ok(await db.prepare('SELECT id FROM orders WHERE id=?').bind(orderId).first())});
console.log('All '+checks+' server integration checks passed.');
}finally{await mf.dispose()}
