import type {Metadata} from 'next';
import Link from 'next/link';
import {Aperture,ArrowUpRight,UserRound} from 'lucide-react';
import {getChatGPTUser,chatGPTSignOutPath} from './chatgpt-auth';
import {isOwner} from '@/lib/server';
import {Toaster} from '@/components/ui/sonner';
import './globals.css';
export const metadata:Metadata={metadataBase:new URL('https://sina-photo-journal.afsharsn.chatgpt.site'),title:{default:'Sina Afshar — Photo Journal & Photo Lab',template:'%s — Sina Afshar'},description:'A photography journal by Sina Afshar. Explore photographs and their stories, collect original digital images, and plan your next shoot with Photo Lab.',openGraph:{type:'website',siteName:'Sina Afshar Photo Journal',title:'Sina Afshar — Photo Journal & Photo Lab',description:'Photographs, the stories behind them, and the art of getting the shot.'},icons:{icon:'/favicon.svg'}};
export default async function RootLayout({children}:{children:React.ReactNode}){const user=await getChatGPTUser();return <html lang="en"><body><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><Link href="/" className="brand" aria-label="Sina Afshar home"><Aperture size={31} strokeWidth={1.2}/><span>SINA AFSHAR<small>PHOTOGRAPHIC JOURNAL</small></span></Link><nav aria-label="Main navigation"><Link href="/">Journal</Link><Link href="/originals">Originals</Link><Link href="/custom-orders">Custom orders</Link><Link href="/lab">Photo Lab <span className="nav-label">26</span></Link></nav><div className="account-nav">{user?<><Link href="/dashboard" className="account-link"><UserRound size={17}/><span>My collection</span></Link>{isOwner(user)&&<Link className="studio-link" href="/studio">Studio</Link>}<a className="signout-link" href={chatGPTSignOutPath()} target="_top">Sign out</a></>:<Link href="/account" className="account-link"><UserRound size={17}/><span>Sign in / Join</span></Link>}</div></header>{children}<footer className="site-footer"><div className="footer-top"><Link href="/" className="footer-name">Sina Afshar<span>Photographic journal</span></Link><a className="text-link" href="mailto:afsharsn@gmail.com">Get in touch <ArrowUpRight size={17}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Sina Afshar. Photograph credits apply.</span><nav aria-label="Legal"><Link href="/legal/privacy">Privacy</Link><Link href="/legal/cookies">Cookies</Link><Link href="/legal/terms">Terms</Link><Link href="/legal/license">Licence</Link><Link href="/legal/withdrawal">Returns & withdrawal</Link></nav></div></footer><Toaster richColors/></body></html>}
