import {identity,readJson,checkOrigin,db,json,fail,HttpError,commerceStatus,runtime,origin,limitAction} from '@/lib/server';
import {PERSONAL_LICENSE,TERMS_VERSION} from '@/lib/content';
import {stripeRequest,settle,type Order} from '@/lib/payments';
export async function POST(request:Request){try{checkOrigin(request);const u=await identity();await limitAction(u.userId,'checkout',5);if(!commerceStatus().enabled)throw new HttpError(503,'Original photograph sales are not open yet.');const b=await readJson(request);if(b.licenseAccepted!==true||b.immediateDelivery!==true||typeof b.photo_id!=='string')throw new HttpError(400,'Please accept the licence and immediate delivery terms.');if(!await db().prepare('SELECT user_id FROM profiles WHERE user_id=?').bind(u.userId).first())throw new HttpError(409,'Create your collection from the dashboard before purchasing.');
const p=await db().prepare('SELECT id,title,price_cents,original_key FROM photos WHERE id=? AND published=1').bind(b.photo_id).first<{id:string;title:string;price_cents:number;original_key:string}>();if(!p||p.price_cents<100)throw new HttpError(404,'This photograph is not available for sale.');if(await db().prepare("SELECT id FROM orders WHERE user_id=? AND photo_id=? AND status='paid'").bind(u.userId,p.id).first())throw new HttpError(409,'You already own this photograph. Download it from your collection.');
const id=crypto.randomUUID(),now=new Date().toISOString(),e=runtime();const seller={name:e.SELLER_NAME,address:e.SELLER_ADDRESS,email:e.SELLER_EMAIL,phone:e.SELLER_PHONE,tax_id:e.SELLER_TAX_ID};await db().prepare('INSERT OR IGNORE INTO orders (id,user_id,photo_id,photo_title,amount,currency,status,created_at,consent_at,terms_version,license_text,seller_snapshot,buyer_email) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,u.userId,p.id,p.title,p.price_cents,'eur','pending',now,now,TERMS_VERSION,PERSONAL_LICENSE,JSON.stringify(seller),u.email).run();
const order=await db().prepare("SELECT * FROM orders WHERE user_id=? AND photo_id=? AND status IN ('pending','paid')").bind(u.userId,p.id).first<Order>();
if(!order)throw new HttpError(503,'Please try again. Your order could not be reserved.');
if(order.status==='paid')throw new HttpError(409,'You already own this photograph. Open your collection.');
if(order.stripe_session_id){
  const existing=await stripeRequest('checkout/sessions/'+encodeURIComponent(order.stripe_session_id));
  if(existing.status==='open'&&existing.url&&new URL(existing.url).hostname==='checkout.stripe.com')return json({url:existing.url,order:order.id});
  if(existing.status==='complete'){await settle(existing);throw new HttpError(409,'Your checkout is complete. Open your collection to check delivery.');}
  if(existing.status==='expired'){await db().prepare("UPDATE orders SET status='expired' WHERE id=? AND status='pending'").bind(order.id).run();throw new HttpError(409,'Your previous checkout expired. Please start again.');}
  throw new HttpError(409,'This order is being processed. Check your collection before retrying.');
}
// A stable order ID and database uniqueness protect retries and concurrent tabs.
// Stop ambiguous old requests before the provider's idempotency key can expire.
if(Date.now()-Date.parse(order.created_at)>20*60*1000)throw new HttpError(409,'An earlier checkout needs review. Please contact the photographer with order '+order.id+'.');
const q=new URLSearchParams({'mode':'payment','adaptive_pricing[enabled]':'false','success_url':origin()+'/dashboard?order='+order.id,'cancel_url':origin()+'/dashboard?cancelled=1','customer_email':order.buyer_email,'expires_at':String(Math.floor(Date.parse(order.created_at)/1000)+3600),'billing_address_collection':'required','automatic_tax[enabled]':'true','tax_id_collection[enabled]':'true','line_items[0][quantity]':'1','line_items[0][price_data][currency]':'eur','line_items[0][price_data][unit_amount]':String(order.amount),'line_items[0][price_data][tax_behavior]':'inclusive','line_items[0][price_data][product_data][name]':order.photo_title+' — original digital photograph','line_items[0][price_data][product_data][description]':'Personal-use licence. Digital file only. Immediate delivery requested; withdrawal right ends when downloading begins.','line_items[0][price_data][product_data][tax_code]':e.STRIPE_TAX_CODE!,'metadata[order_id]':order.id,'metadata[user_id]':u.userId,'metadata[photo_id]':p.id,'payment_intent_data[metadata][order_id]':order.id,'custom_text[submit][message]':'By paying you order this digital photograph with an obligation to pay. Personal-use licence only. Your express consent to immediate delivery is recorded.'});
const s=await stripeRequest('checkout/sessions',q,'photo-order-'+order.id);await db().prepare('UPDATE orders SET stripe_session_id=? WHERE id=?').bind(s.id,order.id).run();if(!s.url||new URL(s.url).hostname!=='checkout.stripe.com')throw new HttpError(503,'The checkout could not be opened.');return json({url:s.url,order:order.id})}catch(e){return fail(e)}}
