export type Photo={id:string;slug:string;title:string;caption:string;alt:string;category:string;location:string;camera:string;lens:string;settings:string;created_at:string;preview:string;price_cents:number;published:number;original_size:number;original_type:string;original_name:string;width:number;height:number;demo?:boolean;credit?:string;source?:string};
export const demoPhotos:Photo[]=[
{id:'sample-alpine',slug:'sample-alpine',title:'Where the world grows quiet',caption:'A study in stillness: mountain, water, and the space between. This is a AI-generated sample image, shown to introduce the journal.',alt:'An alpine lake below dramatic mountain peaks',category:'Landscape',location:'Alpine landscape',preview:'/images/alpine.jpg',credit:'AI-generated sample',source:''},
{id:'sample-coast',slug:'sample-coast',title:'At the edge of the blue',caption:'The meeting of land and sea. A AI-generated sample image for this journal.',alt:'Rugged coastal cliffs overlooking the sea',category:'Travel',location:'Coastal landscape',preview:'/images/coast.jpg',credit:'AI-generated sample',source:''},
{id:'sample-forest',slug:'sample-forest',title:'A different kind of light',caption:'Soft light among the trees. A AI-generated sample image for this journal.',alt:'Atmospheric light in a quiet forest',category:'Nature',location:'Forest landscape',preview:'/images/forest.jpg',credit:'AI-generated sample',source:''},
].map(p=>({...p,camera:'',lens:'',settings:'',created_at:'2026-09-12',price_cents:0,published:1,original_size:0,original_type:'',original_name:'',width:p.id==='sample-alpine'?1536:1024,height:p.id==='sample-alpine'?1024:1536,demo:true}));
export const categories=['Landscape','Street','Portrait','Nature','Travel','Night','Other'];
export const money=(cents:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(cents/100);
export const TERMS_VERSION='2026-09-12';
export const PERSONAL_LICENSE='Personal use: a non-exclusive, non-transferable licence to download, keep and print the photograph for your own private use. Copyright remains with the photographer. No resale, redistribution, advertising, commercial use, sublicensing or AI model training. This is a digital file, not a physical print or transfer of copyright. Mandatory consumer rights are unaffected.';
