import {sessionMatches} from './payment-checks';
export {sessionMatches,verifyStripeSignature} from './payment-checks';
import {db,runtime,origin,HttpError} from './server';
import {money} from './content';
export type Order={id:string;user_id:string;photo_id:string;photo_title:string;amount:number;currency:string;status:string;stripe_session_id:string|null;payment_intent:string|null;created_at:string;paid_at:string|null;consent_at:string;terms_version:string;license_text:string;seller_snapshot:string;downloaded_at:string|null;receipt_sent_at:string|null;buyer_email:string};
export type StripeSession={id:string;payment_status:string;status:string;amount_total:number;currency:string;payment_intent:string|null;url?:string;metadata?:Record<string,string>};
export async function stripeRequest(path:string,params?:URLSearchParams,key?:string){const secret=runtime().STRIPE_SECRET_KEY;if(!secret)throw new HttpError(503,'Purchases are not available yet.');const r=await fetch('https://api.stripe.com/v1/'+path,{method:params?'POST':'GET',headers:{Authorization:'Bearer '+secret,...(params?{'Content-Type':'application/x-www-form-urlencoded'}:{}),...(key?{'Idempotency-Key':key}:{})},body:params?.toString()});const b=await r.json() as StripeSession&{error?:{message?:string}};if(!r.ok){console.error('Payment provider rejected request',r.status);throw new HttpError(503,'The payment provider could not complete this request. Please try again.')}return b}
export function orderConfirmation(o:Order){const seller=JSON.parse(o.seller_snapshot);return ['PHOTO JOURNAL — ORDER CONFIRMATION','Order: '+o.id,'Photograph: '+o.photo_title,'Total paid: '+money(o.amount)+' (inclusive of applicable taxes)','Payment date: '+(o.paid_at||o.created_at),'Customer: '+o.buyer_email,'','Seller: '+seller.name,seller.address,'Email: '+seller.email,'Telephone: '+seller.phone,'Tax status: '+seller.tax_id,'','DIGITAL DELIVERY','A digital photograph for personal use. No physical goods are shipped. Your original is available in your collection: '+origin()+'/dashboard','','LICENCE',o.license_text,'','EXPRESS CONSENT','At '+o.consent_at+' you requested immediate digital delivery and acknowledged that the statutory withdrawal right is lost once downloading begins. Consent applies to terms version '+o.terms_version+'. Before downloading begins you may submit a withdrawal request. Statutory remedies for faulty or non-conforming content remain available.','','RETURNS AND SUPPORT','Use '+origin()+'/legal/withdrawal or email '+seller.email+'. You can request a remedy for inaccessible, damaged or incorrect files. This confirmation does not limit mandatory consumer rights.',''].join('\n')}
export async function emailReceipt(o:Order){if(o.receipt_sent_at)return;const e=runtime();if(!e.RESEND_API_KEY||!e.RECEIPT_FROM_EMAIL)throw new HttpError(503,'Your payment is recorded. Delivery is waiting for the order confirmation service.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+e.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':'receipt-'+o.id},body:JSON.stringify({from:e.RECEIPT_FROM_EMAIL,to:[o.buyer_email],subject:'Your photograph: '+o.photo_title,reply_to:e.SELLER_EMAIL,text:orderConfirmation(o)})});if(!r.ok)throw new HttpError(503,'Your payment is recorded. Please retry shortly while your order confirmation is delivered.');await db().prepare('UPDATE orders SET receipt_sent_at=? WHERE id=?').bind(new Date().toISOString(),o.id).run()}
export async function settle(session:StripeSession){const id=session.metadata?.order_id;if(!id)return;const o=await db().prepare('SELECT * FROM orders WHERE id=?').bind(id).first<Order>();if(!o||!sessionMatches(o,session))return;if(!['pending','paid'].includes(o.status))return;const now=new Date().toISOString();const update=await db().prepare("UPDATE orders SET status='paid',paid_at=COALESCE(paid_at,?),payment_intent=? WHERE id=? AND status IN ('pending','paid')").bind(now,session.payment_intent,o.id).run();if(!update.meta.changes)return;await emailReceipt({...o,status:'paid',paid_at:o.paid_at||now})}
