import {env} from 'cloudflare:workers';
import {getChatGPTUser,type ChatGPTUser} from '@/app/chatgpt-auth';
import {Photo} from './content';
type Runtime={DB:D1Database;BUCKET:R2Bucket;SITE_URL?:string;OWNER_EMAIL?:string;OWNER_USER_ID?:string;STRIPE_SECRET_KEY?:string;STRIPE_WEBHOOK_SECRET?:string;SELLER_NAME?:string;SELLER_ADDRESS?:string;SELLER_EMAIL?:string;SELLER_PHONE?:string;SELLER_TAX_ID?:string;TAX_REVIEWED?:string;LEGAL_REVIEWED?:string;COMMERCE_ENABLED?:string;STRIPE_TAX_CODE?:string;RESEND_API_KEY?:string;RECEIPT_FROM_EMAIL?:string};
export const runtime=()=>env as unknown as Runtime;
export const db=()=>runtime().DB;
export const bucket=()=>runtime().BUCKET;
export const origin=()=>runtime().SITE_URL||'https://sina-photo-journal.afsharsn.chatgpt.site';
export function isOwner(user:ChatGPTUser|null){if(!user)return false;const e=runtime();return e.OWNER_USER_ID?user.userId===e.OWNER_USER_ID:!!e.OWNER_EMAIL&&user.email.toLowerCase()===e.OWNER_EMAIL.toLowerCase()}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export async function identity(owner=false){const u=await getChatGPTUser();if(!u)throw new HttpError(401,'Please sign in to continue.');if(owner&&!isOwner(u))throw new HttpError(403,'This action is available to the photographer only.');return u}
export function checkOrigin(request:Request){if(request.headers.get('origin')!==new URL(request.url).origin)throw new HttpError(403,'Please submit this request from the website.')}
export function fail(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status,headers:{'Cache-Control':'no-store'}});console.error('Request failed',error instanceof Error?error.message:'Unknown error');return Response.json({error:'The service is temporarily unavailable. Your changes have not been saved. Please try again.'},{status:503,headers:{'Cache-Control':'no-store'}})}
export const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
export const photoColumns='id,slug,title,caption,alt,category,location,camera,lens,settings,created_at,price_cents,published,original_size,original_type,original_name,width,height';
export function mapPhoto(row:Record<string,unknown>):Photo{return {...row,preview:`/api/preview/${row.id}`} as unknown as Photo}
export async function publicPhotos(){try{const {results}=await db().prepare(`SELECT ${photoColumns} FROM photos WHERE published=1 ORDER BY created_at DESC LIMIT 100`).all();return {photos:results.map(mapPhoto),unavailable:false}}catch(e){console.error('Journal unavailable',e instanceof Error?e.message:'Storage error');return {photos:[] as Photo[],unavailable:true}}}
export async function findPhoto(slug:string){const r=await db().prepare(`SELECT ${photoColumns} FROM photos WHERE slug=? AND published=1`).bind(slug).first();return r?mapPhoto(r):null}
export function commerceStatus(){const e=runtime();const missing=[!e.STRIPE_SECRET_KEY&&'Stripe server API key',!e.STRIPE_WEBHOOK_SECRET&&'Stripe webhook signing secret',!e.SELLER_NAME&&'Legal seller name',!e.SELLER_ADDRESS&&'Seller postal address',!e.SELLER_EMAIL&&'Seller contact email',!e.SELLER_PHONE&&'Seller telephone',!e.SELLER_TAX_ID&&'Tax status / registration disclosure',e.TAX_REVIEWED!=='true'&&'Tax configuration review',e.LEGAL_REVIEWED!=='true'&&'Legal policy review',!e.STRIPE_TAX_CODE&&'Digital photograph tax classification',(!e.RESEND_API_KEY||!e.RECEIPT_FROM_EMAIL)&&'Verified receipt email sender'].filter(Boolean) as string[];return {enabled:e.COMMERCE_ENABLED==='true'&&missing.length===0,missing}}
export async function limitAction(userId:string,action:string,max=15){const now=Date.now();const key=`${action}:${userId}:${Math.floor(now/60000)}`;const row=await db().prepare('INSERT INTO rate_limits (id,count,expires_at) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+120000).first<{count:number}>();if((row?.count??max+1)>max)throw new HttpError(429,'Too many requests. Please wait one minute and try again.');await db().prepare('DELETE FROM rate_limits WHERE expires_at < ?').bind(now).run()}

export async function readJson(request:Request){if(Number(request.headers.get('content-length'))>65536)throw new HttpError(413,'Request too large.');const text=await request.text();if(text.length>65536)throw new HttpError(413,'Request too large.');try{const v=JSON.parse(text);if(!v||typeof v!=='object'||Array.isArray(v))throw new Error();return v as Record<string,unknown>}catch{throw new HttpError(400,'The request is not valid JSON.')}}
