import {db,commerceStatus,runtime,photoColumns,mapPhoto,HttpError} from './server';
import type {StudioData,StudioStats} from './studio-model';
export async function studioData(params:URLSearchParams):Promise<StudioData>{
 const view=params.get('view')||'overview';const q=(params.get('q')||'').trim();if(q.length>120)throw new HttpError(400,'Keep searches under 120 characters.');const requested=Number(params.get('page')||1);if(!Number.isInteger(requested)||requested<1||requested>10000)throw new HttpError(400,'Invalid page.');const size=params.get('export')==='csv'?5000:24;
 if(view==='overview'||view==='settings'){
  const [photos,customers,orders,support,custom,trend,recent]=await Promise.all([
   db().prepare('SELECT COUNT(*) AS photos, COALESCE(SUM(published),0) AS published, COALESCE(SUM(CASE WHEN published=1 AND price_cents>0 THEN 1 ELSE 0 END),0) AS for_sale, COALESCE(SUM(original_size),0) AS storage FROM photos').first(),
   db().prepare('SELECT COUNT(*) AS customers FROM profiles').first(),
   db().prepare("SELECT COALESCE(SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END),0) AS paid_orders, COALESCE(SUM(CASE WHEN status='paid' THEN amount ELSE 0 END),0) AS gross_paid, COALESCE(SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END),0) AS pending_orders FROM orders").first(),
   db().prepare("SELECT COUNT(*) AS open_requests FROM customer_requests WHERE status='open'").first(),
   db().prepare("SELECT COUNT(*) AS active_custom FROM custom_orders WHERE status NOT IN ('completed','cancelled','declined')").first(),
   db().prepare("SELECT substr(COALESCE(paid_at,created_at),1,7) AS month, SUM(amount) AS amount, COUNT(*) AS count FROM orders WHERE status='paid' AND COALESCE(paid_at,created_at)>=date('now','start of month','-5 months') GROUP BY month ORDER BY month").all(),
   db().prepare('SELECT id,photo_id,photo_title,buyer_email,amount,currency,status,created_at,paid_at,downloaded_at,receipt_sent_at,stripe_session_id,payment_intent,license_text,terms_version FROM orders ORDER BY created_at DESC LIMIT 6').all()
  ]);const status=commerceStatus(),e=runtime();return {rows:recent.results as StudioData['rows'],total:0,page:1,pages:1,stats:{...photos,...customers,...orders,...support,...custom} as StudioStats,trend:trend.results as StudioData['trend'],enabled:status.enabled,missing:status.missing,seller:{'Legal seller':e.SELLER_NAME||'Not provided','Address':e.SELLER_ADDRESS||'Not provided','Contact email':e.SELLER_EMAIL||'Not provided','Telephone':e.SELLER_PHONE||'Not provided','Tax disclosure':e.SELLER_TAX_ID||'Not provided'}};
 }
 const term='%'+q.replace(/[\\%_]/g,'\\$&')+'%',args:unknown[]=[],conditions:string[]=[];let table='',columns='*',sort='created_at DESC',status=params.get('status')||'all';
 if(view==='posts'){table='photos';columns=photoColumns;if(!['all','published','draft','sale','journal'].includes(status))throw new HttpError(400,'Invalid post filter.');if(status==='published')conditions.push('published=1');if(status==='draft')conditions.push('published=0');if(status==='sale')conditions.push('price_cents>0');if(status==='journal')conditions.push('price_cents=0');if(q){conditions.push("(title LIKE ? ESCAPE '\\' OR caption LIKE ? ESCAPE '\\')");args.push(term,term)}const category=params.get('category');if(category){conditions.push('category=?');args.push(category)}}
 else if(view==='sales'){table='orders';columns='id,photo_id,photo_title,buyer_email,amount,currency,status,created_at,paid_at,downloaded_at,receipt_sent_at,stripe_session_id,payment_intent,license_text,terms_version';if(!['all','pending','paid','expired','cancelled','refunded','disputed','failed'].includes(status))throw new HttpError(400,'Invalid order filter.');if(status!=='all'){conditions.push('status=?');args.push(status)}if(q){conditions.push("(photo_title LIKE ? ESCAPE '\\' OR buyer_email LIKE ? ESCAPE '\\' OR id LIKE ? ESCAPE '\\')");args.push(term,term,term)}for(const key of ['from','to']){const day=params.get(key);if(day){if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(Date.parse(day))||new Date(day).toISOString().slice(0,10)!==day)throw new HttpError(400,'Choose valid dates.');conditions.push(key==='from'?'created_at>=?':'created_at<=?');args.push(day+(key==='from'?'T00:00:00.000Z':'T23:59:59.999Z'))}}}
 else if(view==='customers'){table='profiles p';columns="p.*, (SELECT COUNT(*) FROM orders o WHERE o.user_id=p.user_id AND o.status='paid') AS paid_orders, (SELECT COALESCE(SUM(amount),0) FROM orders o WHERE o.user_id=p.user_id AND o.status='paid') AS spent";sort='p.created_at DESC';if(q){conditions.push("(p.name LIKE ? ESCAPE '\\' OR p.email LIKE ? ESCAPE '\\')");args.push(term,term)}}
 else if(view==='custom'){table='custom_orders';if(status!=='all'){if(!['submitted','reviewing','quoted','interested','completed','cancelled','declined'].includes(status))throw new HttpError(400,'Invalid custom-order filter.');conditions.push('status=?');args.push(status)}if(q){conditions.push("(title LIKE ? ESCAPE '\\' OR contact_email LIKE ? ESCAPE '\\')");args.push(term,term)}}
 else if(view==='support'){table='customer_requests';if(!['all','open','resolved'].includes(status))throw new HttpError(400,'Invalid support filter.');if(status!=='all'){conditions.push('status=?');args.push(status)}if(q){conditions.push("(message LIKE ? ESCAPE '\\' OR contact_email LIKE ? ESCAPE '\\' OR order_id LIKE ? ESCAPE '\\')");args.push(term,term,term)}}
 else throw new HttpError(400,'Choose a dashboard section.');
 const where=conditions.length?' WHERE '+conditions.join(' AND '):'';const count=await db().prepare('SELECT COUNT(*) AS total FROM '+table+where).bind(...args).first<{total:number}>();const total=count?.total||0,pages=Math.max(1,Math.ceil(total/size)),page=Math.min(requested,pages);
 const rows=await db().prepare('SELECT '+columns+' FROM '+table+where+' ORDER BY '+sort+' LIMIT ? OFFSET ?').bind(...args,size,(page-1)*size).all();return {rows:view==='posts'?rows.results.map(mapPhoto):rows.results as StudioData['rows'],total,page,pages};
}
