'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {CheckField} from './fields';
import {api} from '@/lib/client';
export function AccountForm({signedIn=false}:{signedIn?:boolean}){const [accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();
async function join(){setBusy(true);setError('');try{await api('/api/account',{accept:accepted});router.push('/dashboard');router.refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <div className="account-form">{signedIn?<><p className="eyebrow">Your space for photography</p><h1>Create your collection.</h1><p className="muted">Keep favourite frames, save shooting setups and access purchased originals in one place.</p><CheckField checked={accepted} onChange={setAccepted}>I accept the <Link href="/legal/terms">terms</Link> and have read the <Link href="/legal/privacy">privacy notice</Link>.</CheckField><button disabled={!accepted||busy} className="button full" onClick={join}>{busy?'Creating…':'Create my collection'}</button></>:<Tabs defaultValue="signin"><TabsList className="tabs-list"><TabsTrigger value="signin">Sign in</TabsTrigger><TabsTrigger value="signup">Join</TabsTrigger></TabsList><TabsContent value="signin"><p className="eyebrow">A space of your own</p><h1>Welcome back.</h1><p className="muted">Open your collection, purchased originals and saved Photo Lab setups.</p><a className="button full" href="/signin-with-chatgpt?return_to=%2Fdashboard" target="_top">Continue with ChatGPT</a></TabsContent><TabsContent value="signup"><p className="eyebrow">For people who look closer</p><h1>Start a collection.</h1><p className="muted">Use your ChatGPT account to join. New here? You can create a ChatGPT account during sign-in, then create your collection.</p><a className="button full" href="/signin-with-chatgpt?return_to=%2Fdashboard" target="_top">Join with ChatGPT</a></TabsContent><p className="muted" style={{marginTop:20,fontSize:'.76rem'}}>Authentication is provided by ChatGPT. Your password is never shared with this website. <Link href="/legal/privacy">Privacy notice</Link></p></Tabs>}{error&&<p role="alert" className="notice error" style={{marginTop:15}}>{error}</p>}</div>}
