'use client';
import {useEffect,useRef,useState} from 'react';
import {LayoutDashboard,Images,Plus,Receipt,Users,MessageSquare,LifeBuoy,Settings,ArrowUpRight,Search,RefreshCw,Download} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {SelectField} from './fields';
import {PostComposer} from './studio';
import {CustomOrdersPanel} from './custom-orders-panel';
import {type Photo,categories,money} from '@/lib/content';
import {customStatuses,statusLabel,type CustomOrder} from '@/lib/custom-orders';
import {type StudioData,type StudioView,type StudioOrder,type StudioCustomer,type StudioRequest} from '@/lib/studio-model';
import {api} from '@/lib/client';
import {toast} from 'sonner';
const views:{id:StudioView;label:string;icon:typeof Images}[]=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'posts',label:'Posts & shop',icon:Images},{id:'create',label:'New post',icon:Plus},{id:'sales',label:'Sales & orders',icon:Receipt},{id:'customers',label:'Customers',icon:Users},{id:'custom',label:'Custom orders',icon:MessageSquare},{id:'support',label:'Customer support',icon:LifeBuoy},{id:'settings',label:'Shop readiness',icon:Settings}];
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('en-GB',{timeZone:'UTC'}):'—';
const fullDate=(v:string|null)=>v?new Date(v).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC':'Not yet';
const freshFilters=()=>({q:'',status:'all',category:'',from:'',to:'',page:1});
export function AdminDashboard({initial,initialView='overview',name}:{initial:StudioData;initialView?:StudioView;name:string}){
 const [view,setView]=useState<StudioView>(initialView),[data,setData]=useState<StudioData|null>(initial),[filters,setFilters]=useState(freshFilters),[search,setSearch]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(''),[selection,setSelection]=useState<string[]>([]),[editing,setEditing]=useState<Photo|null>(null),[removing,setRemoving]=useState<Photo|null>(null),[order,setOrder]=useState<StudioOrder|null>(null),[dirty,setDirty]=useState(false),[leave,setLeave]=useState<StudioView|'close'|null>(null);const first=useRef(true);
 const refresh=()=>setRevision(r=>r+1);const filter=(key:string,value:string)=>{setSelection([]);setFilters(f=>({...f,[key]:value,page:1}))};
 const params=new URLSearchParams({view,...filters,page:String(filters.page)});
 useEffect(()=>{if(first.current){first.current=false;return}if(view==='create')return;const controller=new AbortController();setLoading(true);setError('');const query=new URLSearchParams({view,...filters,page:String(filters.page)});void fetch('/api/studio/manage?'+query,{signal:controller.signal}).then(async r=>{const value=await r.json() as StudioData & {error?:string};if(!r.ok)throw new Error(value.error||'Dashboard unavailable.');if(!controller.signal.aborted)setData(value)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[view,filters,revision]);
 function navigate(next:StudioView,query=''){if(dirty){setLeave(next);return}setView(next);setData(null);setFilters({...freshFilters(),q:query});setSearch(query);setSelection([]);setError('');setEditing(null);window.history.replaceState(null,'','/studio?section='+next)}
 async function action(payload:Record<string,unknown>,label:string){setBusy(String(payload.id||payload.action));try{await api('/api/studio/manage',payload);setSelection([]);refresh();toast.success(label)}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 async function deletePhoto(){if(!removing)return;setBusy(removing.id);try{await api('/api/studio/manage',{id:removing.id,confirm:'DELETE'},'DELETE');setRemoving(null);refresh();toast.success('Unused photograph deleted')}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 async function supportAction(r:StudioRequest,retry=false){setBusy(r.id);try{await api('/api/requests',retry?{id:r.id,retry_acknowledgement:true}:{id:r.id,status:r.status==='open'?'resolved':'open'},'PATCH');refresh();toast.success(retry?'Confirmation email accepted':'Request updated')}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 const photos=(view==='posts'?data?.rows||[]:[]) as Photo[],orders=(data?.rows||[]) as StudioOrder[];
 const statusOptions=view==='posts'?[['all','All posts'],['published','Published'],['draft','Draft / archived'],['sale','Priced originals'],['journal','Journal only']]:view==='sales'?['all','paid','pending','expired','refunded','disputed','cancelled','failed'].map(s=>[s,s==='all'?'All orders':s[0].toUpperCase()+s.slice(1)]):view==='support'?[['all','All requests'],['open','Open'],['resolved','Resolved']]:[['all','All requests'],...customStatuses.map(s=>[s,statusLabel(s)])];
 const listed=['posts','sales','customers','custom','support'].includes(view);
 function orderTable(rows:StudioOrder[]){return <Table className="admin-table"><TableHeader><TableRow><TableHead>Photograph / order</TableHead><TableHead>Customer</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Date</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(o=><TableRow key={o.id}><TableCell><strong>{o.photo_title}</strong><small>{o.id.slice(0,12)}</small></TableCell><TableCell>{o.buyer_email}</TableCell><TableCell>{money(o.amount)}</TableCell><TableCell><span className={'admin-status '+o.status}>{o.status}</span></TableCell><TableCell>{date(o.created_at)}</TableCell><TableCell><button className="button secondary small" onClick={()=>setOrder(o)}>Details</button></TableCell></TableRow>)}</TableBody></Table>}
 return <SidebarProvider className="studio-shell"><Sidebar collapsible="none" className="studio-sidebar"><SidebarHeader className="studio-nav-heading"><p className="eyebrow">Photographer studio</p><h2>{name.split(' ')[0]||'Your'}’s workspace</h2><span>Admin access</span></SidebarHeader><SidebarContent><SidebarMenu aria-label="Studio navigation">{views.map(v=><SidebarMenuItem key={v.id}><SidebarMenuButton isActive={view===v.id} onClick={()=>navigate(v.id)} className="studio-nav-button"><v.icon size={18}/><span>{v.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="studio-nav-footer"><a href="/" target="_blank" rel="noopener noreferrer">View your website <ArrowUpRight size={16}/></a><a href="/lab" target="_blank" rel="noopener noreferrer">Open Photo Lab <ArrowUpRight size={16}/></a></div></SidebarContent></Sidebar>
 <div className="studio-content"><header className="admin-heading"><div><p className="eyebrow">Sina Afshar / Studio</p><h1>{views.find(v=>v.id===view)?.label}</h1><p>{view==='overview'?'Your journal, original collection and customer conversations in one place.':view==='posts'?'Create stories, manage visibility and set prices for your original photographs.':view==='sales'?'Review payments, delivery and the licence recorded with each order.':view==='customers'?'Collectors who have created an account on your website.':view==='settings'?'See what is ready and what needs attention before accepting payments.':view==='support'?'Review order, withdrawal, refund and privacy requests.':view==='custom'?'Review briefs, prepare proposals and follow up in private conversations.':'Upload a photograph, write its story and choose how to share it.'}</p></div><div className="button-row">{view!=='create'&&<button className="button secondary small" aria-label="Refresh dashboard" disabled={loading} onClick={refresh}><RefreshCw size={16}/></button>}{view!=='create'&&<button className="button" onClick={()=>navigate('create')}><Plus size={17}/>New post</button>}</div></header>
 {error&&<div className="notice error" role="alert">{error} <button className="text-link" onClick={refresh}>Try again</button></div>}{loading&&<p className="admin-loading" role="status">Loading {views.find(v=>v.id===view)?.label.toLowerCase()}…</p>}
 {view==='create'?<PostComposer onDirty={setDirty} onSaved={()=>{setDirty(false);setView('posts');setFilters(freshFilters());setData(null);setRevision(r=>r+1);toast.success('Photograph saved');window.history.replaceState(null,'','/studio?section=posts')}}/>:<>
 {listed&&<div className="admin-filters"><form onSubmit={e=>{e.preventDefault();filter('q',search)}} className="admin-search"><label className="sr-only" htmlFor="studio-search">Search {view}</label><input id="studio-search" value={search} maxLength={120} onChange={e=>setSearch(e.target.value)} placeholder={view==='posts'?'Search titles and captions…':view==='customers'?'Search names or email…':'Search title, email or reference…'}/><button className="button secondary" aria-label="Search dashboard"><Search size={17}/></button></form>{view!=='customers'&&<SelectField label="Status" value={filters.status} onChange={v=>filter('status',v)} options={statusOptions.map(([value,label])=>({value,label}))}/>}{view==='posts'&&<SelectField label="Category" value={filters.category||'all'} onChange={v=>filter('category',v==='all'?'':v)} options={[{value:'all',label:'Every category'},...categories.map(value=>({value,label:value}))]}/>}{view==='sales'&&<><label>From<input type="date" value={filters.from} onChange={e=>filter('from',e.target.value)}/></label><label>To<input type="date" value={filters.to} onChange={e=>filter('to',e.target.value)}/></label><a className="button secondary small" href={'/api/studio/manage?'+params+'&export=csv'}><Download size={16}/>Export CSV</a></>}<button className="text-link" onClick={()=>{setSearch('');setFilters(freshFilters());setSelection([])}}>Clear filters</button></div>}
 {view==='overview'&&data?.stats&&<><div className="admin-stats">{[{label:'Gross paid orders',value:money(data.stats.gross_paid),note:`${data.stats.paid_orders} paid · before fees and tax`,go:'sales'},{label:'Published posts',value:data.stats.published,note:`${data.stats.photos-data.stats.published} private drafts / archived`,go:'posts'},{label:'Shop originals',value:data.stats.for_sale,note:data.enabled?'Checkout is enabled':'Checkout is currently closed',go:'posts'},{label:'Collectors',value:data.stats.customers,note:'Registered collection accounts',go:'customers'}].map(s=><button className="admin-stat" key={s.label} onClick={()=>navigate(s.go as StudioView)}><span>{s.label}</span><strong>{s.value}</strong><small>{s.note}</small></button>)}</div><div className="admin-overview-grid"><section className="panel"><div className="section-heading"><h2>Recent orders</h2><button className="text-link" onClick={()=>navigate('sales')}>View all</button></div>{data.rows.length?orderTable(orders):<div className="admin-empty"><Receipt size={30}/><h3>Your first sale starts here.</h3><p>Published originals with a price appear in the shop. Orders will arrive here once checkout is ready.</p><button className="button secondary" onClick={()=>navigate('settings')}>Review shop readiness</button></div>}</section><aside className="panel"><h2>Needs your attention</h2><button className="admin-task" onClick={()=>navigate('support')}><span>Open support requests</span><strong>{data.stats.open_requests}</strong></button><button className="admin-task" onClick={()=>navigate('custom')}><span>Active custom enquiries</span><strong>{data.stats.active_custom}</strong></button><button className="admin-task" onClick={()=>navigate('sales')}><span>Pending payments</span><strong>{data.stats.pending_orders}</strong></button><button className="admin-task" onClick={()=>navigate('settings')}><span>Shop setup items</span><strong>{data.missing?.length||0}</strong></button><p className="field-help">Original files stored: {(data.stats.storage/1048576).toFixed(1)} MB. These totals describe your own catalogue.</p></aside></div><section className="panel admin-monthly"><h2>Paid orders by month</h2><p className="field-help">Last six calendar months · excludes orders currently marked refunded or disputed · not a tax or payout report</p>{data.trend?.length?<div className="admin-revenue-bars">{data.trend.map(t=><div key={t.month}><span>{t.month}</span><div><i style={{width:Math.max(2,t.amount/Math.max(...data.trend!.map(t=>t.amount))*100)+'%'}}/></div><strong>{money(t.amount)}</strong><small>{t.count} orders</small></div>)}</div>:<p className="muted">No paid orders in this period.</p>}</section></>}
 {view==='posts'&&data&&<><div className="admin-selection"><label><Checkbox aria-label="Select all posts on this page" checked={!!photos.length&&selection.length===photos.length} onCheckedChange={v=>setSelection(v?photos.map(p=>p.id):[])}/>Select page</label><span>{selection.length?selection.length+' selected':data.total+' photographs'}</span>{selection.length>0&&<><button className="button secondary small" disabled={!!busy} onClick={()=>void action({action:'publish',ids:selection},'Selected posts published')}>Publish selected</button><button className="button secondary small" disabled={!!busy} onClick={()=>void action({action:'archive',ids:selection},'Selected posts archived')}>Archive selected</button></>}</div><div className="admin-post-grid">{photos.map(p=><article className="admin-post-card" key={p.id}><div className="admin-post-image"><img src={p.preview} alt={p.alt} loading="lazy"/><label><Checkbox aria-label={'Select '+p.title} checked={selection.includes(p.id)} onCheckedChange={v=>setSelection(ids=>v?[...ids,p.id]:ids.filter(id=>id!==p.id))}/></label><span className="badge">{p.published?'Published':'Draft / archived'}</span></div><div className="admin-post-text"><p className="eyebrow">{p.category} · {date(p.created_at)}</p><h2>{p.title}</h2><p>{p.caption.slice(0,110)}</p><strong className="admin-post-price">{p.price_cents?money(p.price_cents)+' · original download':'Journal only'}</strong><div className="button-row"><button className="button small" onClick={()=>setEditing(p)}>Edit post</button><button className="button secondary small" disabled={!!busy} onClick={()=>void action({action:p.published?'archive':'publish',ids:[p.id]},p.published?'Post archived':'Post published')}>{p.published?'Archive':'Publish'}</button>{!p.published&&<button className="admin-delete" onClick={()=>setRemoving(p)}>Delete</button>}</div><div className="admin-post-links">{p.published&&<a href={'/journal/'+p.slug} target="_blank" rel="noopener noreferrer">View post ↗</a>}<a href={'/api/studio/original/'+p.id}>Download original</a></div></div></article>)}</div></>}
 {view==='sales'&&data&&<>{data.rows.length>0&&<section className="panel admin-table-panel">{orderTable(orders)}</section>}<p className="field-help">CSV exports include up to 5,000 matching orders. Use the date and status filters for larger collections. Refunds and disputes are handled in Stripe; completed changes are reflected by payment webhooks.</p></>}
 {view==='customers'&&data&&data.rows.length>0&&<section className="panel admin-table-panel"><Table className="admin-table"><TableHeader><TableRow><TableHead>Collector</TableHead><TableHead>Joined</TableHead><TableHead>Paid orders</TableHead><TableHead>Gross paid</TableHead><TableHead>Activity</TableHead></TableRow></TableHeader><TableBody>{(data.rows as StudioCustomer[]).map(c=><TableRow key={c.user_id}><TableCell><strong>{c.name}</strong><small>{c.email}</small></TableCell><TableCell>{date(c.created_at)}</TableCell><TableCell>{c.paid_orders}</TableCell><TableCell>{money(c.spent)}</TableCell><TableCell><button className="button secondary small" onClick={()=>navigate('sales',c.email)}>View orders</button></TableCell></TableRow>)}</TableBody></Table></section>}
 {view==='custom'&&data&&<CustomOrdersPanel owner orders={data.rows as CustomOrder[]} onUpdated={refresh}/>}
 {view==='support'&&data&&<div className="admin-support-list">{(data.rows as StudioRequest[]).map(r=><article className="panel" key={r.id}><div className="section-heading"><div><span className="badge">{r.type}</span> <span className={'admin-status '+r.status}>{r.status}</span><h2>{r.contact_email||'Account request'}</h2></div><span className="muted">{date(r.created_at)}</span></div><p className="support-message">{r.message}</p><p className="field-help">Reference {r.id}{r.order_id?' · Order '+r.order_id:''}</p><div className="button-row"><button className="button secondary small" disabled={!!busy} onClick={()=>void supportAction(r)}>{r.status==='open'?'Mark resolved':'Reopen request'}</button>{!r.acknowledged_at&&<button className="button secondary small" disabled={!!busy} onClick={()=>void supportAction(r,true)}>Retry confirmation email</button>}{r.order_id&&<button className="text-link" onClick={()=>navigate('sales',r.order_id!)}>View order</button>}</div><p className="field-help">{r.acknowledged_at?'Confirmation accepted '+fullDate(r.acknowledged_at):'Email confirmation is pending. Resolving a request does not issue a refund.'}</p></article>)}</div>}
 {view==='settings'&&data&&<div className="admin-settings-grid"><section className="panel"><p className="eyebrow">Checkout status</p><h2>{data.enabled?'Your shop is open.':'Your shop needs setup.'}</h2><p className="muted">Publishing, photo editing and custom enquiries are available independently of checkout.</p>{data.missing?.length?<ul className="readiness-list">{data.missing.map(m=><li key={m}><span>To complete</span>{m}</li>)}</ul>:<p className="notice">All required website settings are present. {data.enabled?'Checkout is enabled.':'The final commerce switch is still off.'}</p>}<a className="button secondary" href="https://dashboard.stripe.com/" target="_blank" rel="noopener noreferrer">Open Stripe dashboard <ArrowUpRight size={17}/></a><p className="field-help">Complete Stripe account verification and configure the payment, receipt and seller settings through the site’s secure hosting settings. This dashboard never displays your secret keys.</p></section><section className="panel"><h2>Seller information</h2><dl className="admin-definition">{Object.entries(data.seller||{}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><h3>Customer policies</h3><div className="admin-policy-links">{[['Terms','terms'],['Privacy','privacy'],['Cookies','cookies'],['Photo licence','license'],['Returns and withdrawal','withdrawal']].map(([label,path])=><a key={path} href={'/legal/'+path} target="_blank" rel="noopener noreferrer">{label} ↗</a>)}</div><p className="field-help">Keep seller details, tax treatment and policies accurate for your business before enabling checkout. CSV sales totals are not a substitute for accounting records.</p></section></div>}
 {listed&&data&&data.rows.length===0&&view!=='custom'&&<div className="admin-empty panel"><Images size={30}/><h2>{filters.q||filters.status!=='all'?'No matching records.':view==='posts'?'Your catalogue starts with a photograph.':'Nothing here yet.'}</h2><p>{view==='posts'?'Create a post or adjust the filters to find an existing photograph.':'New activity will appear here. Try clearing filters if you expected a result.'}</p>{view==='posts'&&<button className="button" onClick={()=>navigate('create')}>Create your first post</button>}</div>}
 {listed&&data&&<div className="admin-pagination"><span>{data.total} records · page {data.page} of {data.pages}</span><div className="button-row"><button className="button secondary small" disabled={loading||data.page<=1} onClick={()=>{setSelection([]);setFilters(f=>({...f,page:data.page-1}))}}>Previous</button><button className="button secondary small" disabled={loading||data.page>=data.pages} onClick={()=>{setSelection([]);setFilters(f=>({...f,page:data.page+1}))}}>Next</button></div></div>}
 </>}
 </div>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v){if(dirty)setLeave('close');else setEditing(null)}}}><DialogContent className="admin-editor-dialog"><DialogHeader><DialogTitle>Edit photograph</DialogTitle><DialogDescription>Update its story, camera details, price and publication status.</DialogDescription></DialogHeader>{editing&&<PostComposer key={editing.id} initial={editing} onDirty={setDirty} onSaved={()=>{setDirty(false);setEditing(null);refresh();toast.success('Post updated')}}/>}</DialogContent></Dialog>
 <Dialog open={!!order} onOpenChange={v=>{if(!v)setOrder(null)}}><DialogContent className="admin-order-dialog"><DialogHeader><DialogTitle>{order?.photo_title}</DialogTitle><DialogDescription>Order {order?.id}</DialogDescription></DialogHeader>{order&&<><dl className="admin-definition">{[['Customer',order.buyer_email],['Amount',money(order.amount)],['Status',order.status],['Created',fullDate(order.created_at)],['Paid',fullDate(order.paid_at)],['Receipt accepted',fullDate(order.receipt_sent_at)],['Original downloaded',fullDate(order.downloaded_at)],['Terms version',order.terms_version]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>Licence recorded with this order</h3><p className="muted">{order.license_text}</p><div className="button-row">{order.stripe_session_id&&['paid','pending'].includes(order.status)&&<button className="button" disabled={!!busy} onClick={async()=>{await action({action:'sync',id:order.id},'Payment and delivery checked');setOrder(null)}}>Check payment / retry receipt</button>}{order.payment_intent&&<a className="button secondary" href={'https://dashboard.stripe.com/payments/'+encodeURIComponent(order.payment_intent)} target="_blank" rel="noopener noreferrer">Manage in Stripe ↗</a>}</div></>}</DialogContent></Dialog>
 <AlertDialog open={!!removing} onOpenChange={v=>{if(!v&&!busy)setRemoving(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete “{removing?.title}”?</AlertDialogTitle><AlertDialogDescription>This permanently removes the unpublished post and its stored files. Photos with any order records cannot be deleted. Keep an external copy if you need it.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={!!busy}>Keep photograph</AlertDialogCancel><button className="button danger" disabled={!!busy} onClick={()=>void deletePhoto()}>{busy?'Deleting…':'Delete permanently'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!leave} onOpenChange={v=>{if(!v)setLeave(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard unsaved post changes?</AlertDialogTitle><AlertDialogDescription>Save the post first to keep your changes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><button className="button danger" onClick={()=>{const next=leave;setLeave(null);setDirty(false);setEditing(null);if(next&&next!=='close'){setView(next);setData(null);setFilters(freshFilters());setSearch('');setSelection([]);window.history.replaceState(null,'','/studio?section='+next)}}}>Discard changes</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>
}
