'use client';
import {useState} from 'react';
import {ArrowUpRight,CheckCircle2} from 'lucide-react';
import {SelectField,CheckField} from './fields';
import {customServices} from '@/lib/custom-orders';
import {api,downloadText} from '@/lib/client';
export function CustomOrderForm(){const[form,setForm]=useState({title:'',service:customServices[0] as string,intended_use:'Personal',brief:'',location:'',target_date:'',budget:''}),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{id:string;received_at:string}|null>(null);const set=(key:keyof typeof form,value:string)=>setForm(f=>({...f,[key]:value}));
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{id:string;received_at:string}>('/api/custom-orders',{...form,budget_cents:form.budget===''?null:Math.round(Number(form.budget)*100),accept:accepted});setResult(r)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
if(result)return <div className="panel commission-success" role="status"><CheckCircle2 size={38}/><h2>Your idea is on the table.</h2><p>The photographer can now review your brief. Return to your collection for proposals and private messages.</p><p className="muted">Reference: {result.id}</p><div className="button-row"><a className="button" href="/dashboard?tab=custom">Track your request <ArrowUpRight size={17}/></a><button className="button secondary" onClick={()=>downloadText('custom-order-request.txt',['Photo Journal — custom request','Reference: '+result.id,'Received: '+result.received_at,'Project: '+form.title,'Service: '+form.service,'Intended use: '+form.intended_use,'Brief: '+form.brief,'Date: '+(form.target_date||'Flexible'),'Budget EUR: '+(form.budget||'To discuss'),'Submitting this enquiry does not create a booking or charge.'].join('\n'))}>Save request copy</button></div></div>;
return <form className="panel form-stack" onSubmit={submit}><div><p className="eyebrow">Start a conversation</p><h2 style={{marginTop:8}}>Tell me what you have in mind.</h2><p className="muted">A clear brief is a good beginning. No payment or booking is created by this form.</p></div><label>Project name<input required minLength={3} maxLength={140} value={form.title} onChange={e=>set('title',e.target.value)} placeholder="A portrait, a place, a product, an idea…"/></label><div className="form-grid"><SelectField label="What would you like?" value={form.service} onChange={v=>set('service',v)} options={customServices.map(value=>({value,label:value}))}/><SelectField label="Intended use" value={form.intended_use} onChange={v=>set('intended_use',v)} options={['Personal','Editorial','Commercial'].map(value=>({value,label:value}))}/></div><label>Your brief<textarea required minLength={20} maxLength={8000} value={form.brief} onChange={e=>set('brief',e.target.value)} placeholder="Describe the subject, style, number of images, final use and anything else that matters. You can include reference links. Please leave out sensitive personal information."/></label><div className="form-grid"><label>Location, if relevant<input maxLength={200} value={form.location} onChange={e=>set('location',e.target.value)} placeholder="City, studio, or remote"/></label><label>Preferred date (optional)<input type="date" value={form.target_date} onChange={e=>set('target_date',e.target.value)}/></label><label>Budget in euros (optional)<input type="number" min={0} max={100000} step={1} value={form.budget} onChange={e=>set('budget',e.target.value)} placeholder="Leave blank to discuss"/></label></div><CheckField checked={accepted} onChange={setAccepted}>I accept the <a className="inline-link" href="/legal/terms">terms</a> and have read the <a className="inline-link" href="/legal/privacy">privacy notice</a>. Create or use my collection to store this enquiry and contact me about it.</CheckField>{error&&<p className="notice error" role="alert">{error}</p>}<button disabled={busy||!accepted} className="button">{busy?'Sending your brief…':'Send custom request'}<ArrowUpRight size={17}/></button></form>}
