'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SelectField} from './fields';
import {api} from '@/lib/client';
import {money} from '@/lib/content';
import {statusLabel,ownerTransitions,type CustomOrder,type CustomMessage} from '@/lib/custom-orders';
import {toast} from 'sonner';
export function CustomOrdersPanel({orders,owner=false}:{orders:CustomOrder[];owner?:boolean}){
const router=useRouter(),[selected,setSelected]=useState<CustomOrder|null>(null),[messages,setMessages]=useState<CustomMessage[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(''),[reply,setReply]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState('reviewing'),[estimate,setEstimate]=useState(''),[proposal,setProposal]=useState('');
async function open(id:string){setLoading(id);setError('');try{const r=await api<{order:CustomOrder;messages:CustomMessage[]}>('/api/custom-orders?id='+encodeURIComponent(id),undefined,'GET');setSelected(r.order);setMessages(r.messages);setReply('');setStatus(ownerTransitions[r.order.status][0]||r.order.status);setEstimate(r.order.quote_cents===null?'':String(r.order.quote_cents/100));setProposal(r.order.proposal)}catch(e){toast.error((e as Error).message)}finally{setLoading('')}}
async function update(payload:Record<string,unknown>){if(!selected)return;setBusy(true);setError('');try{await api('/api/custom-orders',{id:selected.id,updated_at:selected.updated_at,...payload},'PATCH');await open(selected.id);router.refresh();toast.success(payload.action==='message'?'Message saved':'Request updated')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <><div className="section-heading"><h2>{owner?'Custom requests':'Your custom orders'}</h2>{!owner&&<a className="button secondary small" href="/custom-orders">New request</a>}</div>{orders.length?<div className="panel">{orders.map(o=><article className="order-row" key={o.id}><div><p className="eyebrow">{o.service}</p><h3>{o.title}</h3><p className="muted"><span className="badge">{statusLabel(o.status)}</span> · {new Date(o.created_at).toLocaleDateString('en-GB',{timeZone:'UTC'})}{owner?' · '+o.contact_email:''}</p></div><button className="button secondary small" disabled={loading===o.id} onClick={()=>open(o.id)}>{loading===o.id?'Opening…':'View conversation'}</button></article>)}</div>:<div className="empty-state"><h2>{owner?'Ready for the next idea.':'Have a frame in mind?'}</h2><p>{owner?'Customer briefs will appear here for review, proposals and private replies.':'Custom photographs, edits and licences begin with a conversation.'}</p>{!owner&&<a className="button" href="/custom-orders">Request something personal</a>}</div>}
<Dialog open={!!selected} onOpenChange={v=>{if(!v&&!busy)setSelected(null)}}><DialogContent className="commission-dialog"><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?statusLabel(selected.status)+' · '+selected.service:''}</DialogDescription></DialogHeader>{selected&&<><dl><div><dt>Intended use</dt><dd>{selected.intended_use}</dd></div><div><dt>Preferred date</dt><dd>{selected.target_date||'Flexible'}</dd></div><div><dt>Location</dt><dd>{selected.location||'To discuss'}</dd></div><div><dt>Budget</dt><dd>{selected.budget_cents===null?'To discuss':money(selected.budget_cents)}</dd></div>{owner&&<div><dt>Customer email</dt><dd>{selected.contact_email}</dd></div>}</dl><section><h3>The brief</h3><p className="commission-prose">{selected.brief}</p></section>{selected.proposal&&<section className="proposal-box"><p className="eyebrow">Photographer’s proposal</p><h3>{selected.quote_cents===null?'Scope under discussion':money(selected.quote_cents)+' estimated'}</h3><p className="commission-prose">{selected.proposal}</p><p className="muted">An estimate is not a booking. Final scope, licensing, taxes, delivery, payment and any cancellation terms need a separate written agreement.</p></section>}
{owner&&ownerTransitions[selected.status].length>0&&<form className="dialog-form proposal-editor" onSubmit={e=>{e.preventDefault();void update({status,quote_cents:estimate===''?null:Math.round(Number(estimate)*100),proposal})}}><h3>Manage this request</h3><div className="form-grid"><SelectField label="Status" value={status} onChange={setStatus} options={ownerTransitions[selected.status].map(value=>({value,label:statusLabel(value)}))}/><label>Estimated total (€)<input type="number" min={1} max={100000} step={.01} value={estimate} onChange={e=>setEstimate(e.target.value)}/></label></div><label>Proposal visible to the customer<textarea maxLength={8000} value={proposal} onChange={e=>setProposal(e.target.value)} placeholder="Describe scope, deliverables, intended usage, estimated timing and what the price includes."/></label><button className="button" disabled={busy}>Save proposal and status</button></form>}
{!owner&&<div className="button-row">{selected.status==='quoted'&&<button className="button" disabled={busy} onClick={()=>update({action:'interest'})}>I’m interested — discuss next steps</button>}{['submitted','reviewing','quoted','interested'].includes(selected.status)&&<button className="button secondary" disabled={busy} onClick={()=>update({action:'cancel'})}>Cancel this enquiry</button>}</div>}
<section className="commission-thread"><h3>Private conversation</h3>{messages.length?messages.map(m=><article className={'commission-message '+m.author_role} key={m.id}><p className="eyebrow">{m.author_role==='photographer'?'Photographer':'Customer'} · {new Date(m.created_at).toLocaleString('en-GB')}</p><p className="commission-prose">{m.body}</p></article>):<p className="muted">Ask questions and discuss the details here.</p>}<form className="dialog-form" onSubmit={e=>{e.preventDefault();void update({action:'message',body:reply})}}><label>Your message<textarea required minLength={3} maxLength={4000} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a private reply…"/></label><button disabled={busy||reply.trim().length<3} className="button secondary">{busy?'Saving…':'Send message'}</button></form></section><p className="muted">Reference {selected.id}. Check this conversation for replies; email notifications are not sent automatically.</p>{error&&<p className="notice error" role="alert">{error}</p>}</>}</DialogContent></Dialog></>}
