'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Bookmark,Share2,ArrowUpRight} from 'lucide-react';
import {toast} from 'sonner';
import {Photo,money} from '@/lib/content';
import {api} from '@/lib/client';
import {CheckField} from './fields';
export function PhotoActions({photo:p,signedIn,canBuy,ownedOrder,initialSaved=false}:{photo:Photo;signedIn:boolean;canBuy:boolean;ownedOrder?:string;initialSaved?:boolean}){const[saved,setSaved]=useState(initialSaved),[license,setLicense]=useState(false),[delivery,setDelivery]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
async function bookmark(){if(!signedIn){window.location.href='/account';return}try{const r=await api<{saved:boolean}>('/api/bookmarks',{photo_id:p.id});setSaved(r.saved);toast.success(r.saved?'Added to your favourites':'Removed from favourites')}catch(e){toast.error((e as Error).message)}}
async function buy(){setBusy(true);setError('');try{const r=await api<{url:string}>('/api/checkout',{photo_id:p.id,licenseAccepted:license,immediateDelivery:delivery});window.location.assign(r.url)}catch(e){setError((e as Error).message);setBusy(false)}}
async function share(){try{await navigator.clipboard.writeText(window.location.href);toast.success('Link copied')}catch{toast.error('Copy this page’s address from your browser to share it.')}}
return <><div className="button-row">{!p.demo&&<button className="button secondary small" aria-pressed={saved} onClick={bookmark}><Bookmark size={15} fill={saved?'currentColor':'none'}/>{saved?'Saved':'Save frame'}</button>}<button className="button secondary small" onClick={share}><Share2 size={15}/>Share</button></div>{p.demo?<div className="purchase-box"><p className="eyebrow">Sample photograph</p><p className="muted">This image is an AI-generated example, not a photograph by Sina. It is not for sale.</p></div>:p.price_cents>0?<div className="purchase-box"><p className="eyebrow">Collect the original</p><div className="price-large">{money(p.price_cents)}</div><p className="muted">{p.width} × {p.height} px · {(p.original_size/1024/1024).toFixed(1)} MB · {p.original_type.replace('image/','').toUpperCase()}</p><p className="muted">Digital download · Personal use · Total includes applicable taxes.</p>{ownedOrder?<Link href="/dashboard" className="button full">Open in my collection <ArrowUpRight size={17}/></Link>:!canBuy?<p className="notice" style={{marginTop:20}}>Sales are not open yet.</p>:!signedIn?<Link className="button full" href="/account">Sign in to collect</Link>:<><CheckField checked={license} onChange={setLicense}>I accept the <Link href="/legal/license" style={{textDecoration:'underline'}}>personal-use licence</Link> and <Link href="/legal/terms" style={{textDecoration:'underline'}}>sales terms</Link>.</CheckField><CheckField checked={delivery} onChange={setDelivery}>I request immediate digital delivery and acknowledge that I lose my statutory right of withdrawal once I start downloading. My rights for faulty content remain.</CheckField><button className="button full" disabled={!license||!delivery||busy} onClick={buy}>{busy?'Opening checkout…':'Continue to pay '+money(p.price_cents)}</button><p className="muted" style={{fontSize:'.72rem',marginTop:10}}>Secure payment with Stripe. An order confirmation is emailed before your download.</p></>}{error&&<p role="alert" className="notice error" style={{marginTop:15}}>{error}</p>}</div>:null}</>}
