'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import PhotoFilterWorker from '../lib/photo-filter.worker?worker';
import {Upload,Download,Undo2,Redo2,RotateCcw,SlidersHorizontal,SplitSquareHorizontal} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Progress} from '@/components/ui/progress';
import {SelectField} from './fields';
import {downloadText} from '@/lib/client';
import {adjustmentControls,neutral,photoPresets,parseRecipe,type EditRecipe} from '@/lib/photo-filters';
const emptyRecipe=():EditRecipe=>({version:1,presetId:'original',strength:100,adjustments:{...neutral}});
const makeWorker=()=>new PhotoFilterWorker();
function requestWorker(worker:Worker,message:Record<string,unknown>,transfer:Transferable[]=[]):Promise<{data:Uint8ClampedArray;thumbnails?:{id:string;data:Uint8ClampedArray}[]}>{return new Promise((resolve,reject)=>{const done=()=>{worker.removeEventListener('message',messageHandler);worker.removeEventListener('error',errorHandler)};const messageHandler=(e:MessageEvent)=>{done();if(e.data.error)reject(new Error(e.data.error));else resolve(e.data)};const errorHandler=()=>{done();reject(new Error('Photo processing stopped. Try a smaller export size or reopen the photo.'))};worker.addEventListener('message',messageHandler);worker.addEventListener('error',errorHandler);worker.postMessage(message,{transfer})})}
function canvasBlob(canvas:HTMLCanvasElement,type:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Your browser could not create this export. Try a smaller size.')),type,quality))}
export function PhotoEditor(){
 const bitmap=useRef<ImageBitmap|null>(null),original=useRef<HTMLCanvasElement>(null),processed=useRef<HTMLCanvasElement>(null),picker=useRef<HTMLInputElement>(null),previewWorker=useRef<Worker|null>(null),loadId=useRef(0),cancelExport=useRef(false),committed=useRef<EditRecipe>(emptyRecipe());
 const [photo,setPhoto]=useState<{name:string;width:number;height:number;sample:boolean}|null>(null),[recipe,setRecipe]=useState<EditRecipe>(emptyRecipe),[past,setPast]=useState<EditRecipe[]>([]),[future,setFuture]=useState<EditRecipe[]>([]),[group,setGroup]=useState('All'),[thumbnails,setThumbnails]=useState<Record<string,string>>({}),[loading,setLoading]=useState(false),[processing,setProcessing]=useState(false),[error,setError]=useState(''),[compare,setCompare]=useState(false),[divider,setDivider]=useState(50),[format,setFormat]=useState('image/jpeg'),[exportSize,setExportSize]=useState('original'),[quality,setQuality]=useState(95),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0),[bins,setBins]=useState<number[]>([]);
 const preset=photoPresets.find(p=>p.id===recipe.presetId),groups=useMemo(()=>['All',...new Set(photoPresets.map(p=>p.group))],[]);
 const commit=(next:EditRecipe)=>{const previous=committed.current;setPast(p=>[...p,previous].slice(-40));setFuture([]);committed.current=next;setRecipe(next)};
 function undo(){const previous=past.at(-1);if(!previous)return;const current=committed.current;setFuture(f=>[current,...f]);setPast(p=>p.slice(0,-1));committed.current=previous;setRecipe(previous)}
 function redo(){const next=future[0];if(!next)return;const current=committed.current;setPast(p=>[...p,current]);setFuture(f=>f.slice(1));committed.current=next;setRecipe(next)}
 async function openPhoto(file?:File){const id=++loadId.current;setLoading(true);setError('');let image:ImageBitmap|null=null;try{
  if(file&&(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>40*1024*1024))throw new Error('Choose a JPEG, PNG or WebP photograph under 40 MB. Export RAW or HEIC files to one of these formats first.');
  const response=file?null:await fetch('/images/alpine.jpg');if(response&&!response.ok)throw new Error('The sample could not be loaded. You can open your own photo.');
  image=await createImageBitmap(file||await response!.blob(),{imageOrientation:'from-image'});
  if(image.width*image.height>80000000||Math.max(image.width,image.height)>20000)throw new Error('Choose an image up to 80 megapixels and 20,000 pixels on its longest side.');
  if(id!==loadId.current){image.close();return;}bitmap.current?.close();bitmap.current=image;image=null;
  const next=emptyRecipe();committed.current=next;setRecipe(next);setPast([]);setFuture([]);setThumbnails({});setPhoto({name:file?.name||'sample-alpine.jpg',width:bitmap.current.width,height:bitmap.current.height,sample:!file});
 }catch(e){image?.close();if(id===loadId.current)setError((e as Error).message)}finally{if(id===loadId.current)setLoading(false)}}
 useEffect(()=>{void openPhoto();return()=>{loadId.current++;cancelExport.current=true;bitmap.current?.close();previewWorker.current?.terminate()}},[]);
 useEffect(()=>{
  const image=bitmap.current,canvas=original.current;if(!image||!canvas||!photo)return;
  const scale=Math.min(1,1440/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);
  const tiny=document.createElement('canvas');tiny.width=144;tiny.height=96;const ctx=tiny.getContext('2d')!;const fit=Math.max(tiny.width/image.width,tiny.height/image.height);ctx.drawImage(image,(144-image.width*fit)/2,(96-image.height*fit)/2,image.width*fit,image.height*fit);const pixels=ctx.getImageData(0,0,144,96);let alive=true;let worker:Worker;
  try{worker=makeWorker();void requestWorker(worker,{id:0,width:144,height:96,data:pixels.data,thumbnails:true},[pixels.data.buffer]).then(r=>{if(!alive)return;const urls:Record<string,string>={};for(const t of r.thumbnails||[]){ctx.putImageData(new ImageData(new Uint8ClampedArray(t.data),144,96),0,0);urls[t.id]=tiny.toDataURL('image/jpeg',.78)}setThumbnails(urls)}).catch(()=>{}).finally(()=>worker.terminate());}catch{return;}
  return()=>{alive=false;worker?.terminate()};
 },[photo]);
 useEffect(()=>{
  const canvas=original.current;if(!photo||!canvas)return;let alive=true;setProcessing(true);setError('');previewWorker.current?.terminate();
  const timer=setTimeout(async()=>{try{const pixels=canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height),worker=makeWorker();previewWorker.current=worker;const r=await requestWorker(worker,{id:1,width:canvas.width,height:canvas.height,data:pixels.data,recipe},[pixels.data.buffer]);if(!alive)return;const dest=processed.current!;dest.width=canvas.width;dest.height=canvas.height;dest.getContext('2d')!.putImageData(new ImageData(new Uint8ClampedArray(r.data),canvas.width,canvas.height),0,0);const histogram=Array(64).fill(0);for(let i=0;i<r.data.length;i+=16)if(r.data[i+3])histogram[Math.min(63,Math.floor((r.data[i]*.2126+r.data[i+1]*.7152+r.data[i+2]*.0722)/4))]++;setBins(histogram);setProcessing(false);worker.terminate();}catch(e){if(alive){setError((e as Error).message);setProcessing(false)}}},100);
  return()=>{alive=false;clearTimeout(timer);previewWorker.current?.terminate()};
 },[photo,recipe]);
 async function exportPhoto(){if(!bitmap.current||!photo)return;setError('');setExporting(true);setProgress(0);cancelExport.current=false;let worker:Worker|null=null;const dest=document.createElement('canvas'),tile=document.createElement('canvas');try{
  const image=bitmap.current,longest=Math.max(image.width,image.height),scale=exportSize==='original'?1:Math.min(1,Number(exportSize)/longest);dest.width=Math.round(image.width*scale);dest.height=Math.round(image.height*scale);if(dest.width*dest.height>67000000)throw new Error('Full-size export supports up to 67 megapixels. Choose 4,096 px for this image.');const dc=dest.getContext('2d');if(!dc)throw new Error('Your browser could not allocate this export. Choose a smaller size.');worker=makeWorker();
  // Tiles keep working memory bounded and always sample the untouched source.
  for(let y=0;y<dest.height;y+=256){if(cancelExport.current)throw new Error('Export cancelled. Your edits are still here.');const rows=Math.min(256,dest.height-y),top=y?1:0,bottom=y+rows<dest.height?1:0;tile.width=dest.width;tile.height=rows+top+bottom;const tc=tile.getContext('2d',{willReadFrequently:true})!;tc.drawImage(image,0,(y-top)/scale,image.width,tile.height/scale,0,0,tile.width,tile.height);const data=tc.getImageData(0,0,tile.width,tile.height);const result=await requestWorker(worker,{id:y,data:data.data,width:tile.width,height:tile.height,recipe,offsetY:y-top,fullHeight:dest.height},[data.data.buffer]);dc.putImageData(new ImageData(new Uint8ClampedArray(result.data),tile.width,tile.height),0,y-top,0,top,dest.width,rows);setProgress(Math.round((y+rows)/dest.height*90));}
  if(cancelExport.current)throw new Error('Export cancelled. Your edits are still here.');if(format==='image/jpeg'){dc.globalCompositeOperation='destination-over';dc.fillStyle='#fff';dc.fillRect(0,0,dest.width,dest.height)}const blob=await canvasBlob(dest,format,quality/100);const extension=blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg',url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=photo.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]/g,'_')+'-'+recipe.presetId+'.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setProgress(100);
 }catch(e){setError((e as Error).message)}finally{worker?.terminate();dest.width=dest.height=tile.width=tile.height=0;setExporting(false)}}
 async function importRecipe(file?:File){if(!file)return;try{if(file.size>65536)throw new Error('Choose a Photo Lab settings file under 64 KB.');commit(parseRecipe(JSON.parse(await file.text())));setError('')}catch(e){setError((e as Error).message)}}
 return <section className="photo-editor" aria-label="Photo editor">
  <div className="editor-toolbar"><div><h2>Make the frame yours.</h2><p>24 presets · real pixel edits · private, in-browser processing</p></div><div className="button-row"><input ref={picker} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Open a photo to edit" className="editor-file-input" disabled={loading||exporting} onChange={e=>{void openPhoto(e.target.files?.[0]);e.target.value=''}}/><button className="button" disabled={loading||exporting} onClick={()=>picker.current?.click()}><Upload size={16}/>{loading?'Opening…':'Open photo'}</button><button className="button secondary" disabled={loading||exporting} onClick={()=>void openPhoto()}>Try sample</button></div></div>
  {error&&<p className="notice error" role="alert">{error}</p>}
  <div className="editor-layout"><div className="editor-workspace"><div className="editor-image-bar"><span>{photo?.sample?'Sample image · AI-generated':photo?.name||'Open a photograph'}</span><div className="button-row"><button aria-label="Undo photo edit" title="Undo" disabled={!past.length||exporting} onClick={undo}><Undo2 size={18}/></button><button aria-label="Redo photo edit" title="Redo" disabled={!future.length||exporting} onClick={redo}><Redo2 size={18}/></button><button aria-label="Reset photo edits" title="Reset all edits" disabled={!photo||exporting} onClick={()=>commit(emptyRecipe())}><RotateCcw size={18}/></button><button aria-pressed={compare} disabled={!photo} onClick={()=>setCompare(v=>!v)}><SplitSquareHorizontal size={17}/>Compare</button></div></div>
  <div className="editor-canvas-wrap" style={{aspectRatio:photo?`${photo.width}/${photo.height}`:'3/2'}} aria-label="Photo preview"><canvas ref={original} aria-label="Original photograph"/><canvas ref={processed} className="editor-processed" style={{clipPath:compare?`inset(0 ${100-divider}% 0 0)`:'none'}} aria-label="Edited photograph"/>{compare&&<><span className="editor-before-label">Edited</span><span className="editor-after-label">Original</span><div className="editor-divider" style={{left:divider+'%'}}/></>}{(loading||processing)&&<span className="editor-processing" role="status">{loading?'Opening photo…':'Updating preview…'}</span>}</div>
  {compare&&<div className="editor-compare"><label>Before / after divider</label><Slider aria-label="Before and after divider" value={[divider]} onValueChange={v=>setDivider(v[0])} min={0} max={100}/></div>}
  <div className="editor-photo-info"><span>{photo?`${photo.width.toLocaleString('en-GB')} × ${photo.height.toLocaleString('en-GB')} px`:''}</span><span>{preset?.name||'Original'}{preset?' · '+recipe.strength+'%':''}</span><span>Preview scaled to fit · export uses source pixels</span></div>
  <div className="preset-heading"><h3>Find your starting point.</h3><p>{preset?.description||'Choose a preset, then make it your own with the controls.'}</p></div><div className="preset-categories" aria-label="Preset categories">{groups.map(g=><button key={g} aria-pressed={g===group} onClick={()=>setGroup(g)}>{g}</button>)}</div>
  <div className="preset-grid">{photoPresets.filter(p=>group==='All'||p.group===group).map((p,i)=><button key={p.id} className={'preset-card '+(p.id===recipe.presetId?'selected':'')} aria-pressed={p.id===recipe.presetId} title={p.description} disabled={!photo||exporting} onClick={()=>commit({version:1,presetId:p.id,strength:100,adjustments:{...neutral}})}>{thumbnails[p.id]?<img src={thumbnails[p.id]} alt="" width={144} height={96}/>:<span className="preset-placeholder">{String(i+1).padStart(2,'0')}</span>}<span>{p.name}</span></button>)}</div>
  </div><aside className="editor-controls"><div className="editor-control-heading"><SlidersHorizontal size={17}/><h3>Develop</h3><button onClick={()=>commit(emptyRecipe())} disabled={exporting}>Reset</button></div>
  <svg viewBox="0 0 256 56" role="img" aria-label="Edited image brightness histogram" className="editor-histogram">{bins.map((n,i)=><rect key={i} x={i*4} y={56-n/Math.max(1,...bins)*52} width={3} height={n/Math.max(1,...bins)*52}/>)}</svg><p className="editor-histogram-label">Shadows <span>Highlights</span></p>
  <div className="editor-adjustment"><label>Preset strength <output>{recipe.strength}%</output></label><Slider aria-label="Preset strength" min={0} max={100} value={[recipe.strength]} disabled={recipe.presetId==='original'||exporting} onValueChange={v=>setRecipe(r=>({...r,strength:v[0]}))} onValueCommit={v=>commit({...recipe,strength:v[0]})}/></div>
  {adjustmentControls.map(c=><div className="editor-adjustment" key={c.key}><label>{c.label}<output>{c.key==='exposure'?(recipe.adjustments[c.key]>0?'+':'')+recipe.adjustments[c.key].toFixed(2)+' EV':recipe.adjustments[c.key]}</output></label><Slider aria-label={c.label} min={c.min} max={c.max} step={c.step} value={[recipe.adjustments[c.key]]} disabled={exporting} onValueChange={v=>setRecipe(r=>({...r,adjustments:{...r.adjustments,[c.key]:v[0]}}))} onValueCommit={v=>commit({...recipe,adjustments:{...recipe.adjustments,[c.key]:v[0]}})}/></div>)}
  <details className="editor-export" open><summary>Export photograph</summary><SelectField label="Image format" value={format} onChange={setFormat} options={[{value:'image/jpeg',label:'JPEG · compatible'},{value:'image/png',label:'PNG · lossless, keeps transparency'},{value:'image/webp',label:'WebP · smaller file'}]}/><SelectField label="Export dimensions" value={exportSize} onChange={setExportSize} options={[{value:'original',label:'Original dimensions · up to 67 MP'},{value:'4096',label:'4,096 px long edge'},{value:'2560',label:'2,560 px long edge'},{value:'1600',label:'1,600 px long edge'}]}/>{format!=='image/png'&&<div className="editor-adjustment"><label>Export quality <output>{quality}%</output></label><Slider aria-label="Export quality" min={70} max={100} value={[quality]} onValueChange={v=>setQuality(v[0])}/></div>}<button className="button full" disabled={!photo||loading||exporting} onClick={()=>void exportPhoto()}><Download size={17}/>{exporting?'Exporting…':'Download edited photo'}</button>{exporting&&<div className="editor-export-progress" role="status"><Progress value={progress} aria-label="Image export progress"/><p>{progress}% · processing source pixels</p><button className="text-link" onClick={()=>{cancelExport.current=true}}>Cancel export</button></div>}<p>Edits do not overwrite your original. Exports are 8-bit sRGB; embedded camera and location metadata is removed. Large exports need more memory—choose 4,096 px if your device struggles.</p></details>
  <details className="editor-export"><summary>Reuse these settings</summary><button className="button secondary full" onClick={()=>downloadText('photo-lab-'+recipe.presetId+'.json',JSON.stringify(recipe,null,2),'application/json')}>Save settings file</button><label className="editor-recipe-label">Load a settings file<input type="file" accept="application/json,.json" disabled={exporting} onChange={e=>{void importRecipe(e.target.files?.[0]);e.target.value=''}}/></label></details>
  </aside></div><p className="editor-footnote">JPEG, PNG and WebP, up to 40 MB. Presets adjust existing pixels; they cannot reconstruct missing focus or clipped detail. Sharpening, smoothing and film grain are adjustable so you can choose the finish that suits the photograph.</p>
 </section>
}
