import {identity,checkOrigin,readJson,db,json,fail,HttpError,limitAction,bucket} from '@/lib/server';
import {studioData} from '@/lib/studio-data';
import {csvText,type StudioOrder} from '@/lib/studio-model';
import {stripeRequest,settle,type Order} from '@/lib/payments';
export async function GET(request:Request){try{await identity(true);const params=new URL(request.url).searchParams;const data=await studioData(params);if(params.get('export')==='csv'){if(params.get('view')!=='sales')throw new HttpError(400,'Choose the sales export.');const rows=data.rows as StudioOrder[];return new Response(csvText([['Order','Photograph','Customer','Amount EUR','Status','Created UTC','Paid UTC','Downloaded UTC'],...rows.map(o=>[o.id,o.photo_title,o.buyer_email,(o.amount/100).toFixed(2),o.status,o.created_at,o.paid_at,o.downloaded_at])]),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="photo-journal-sales.csv"','Cache-Control':'private, no-store'}})}return json(data)}catch(e){return fail(e)}}
export async function POST(request:Request){try{checkOrigin(request);const u=await identity(true);await limitAction(u.userId,'studio-manage',20);const b=await readJson(request);
 if(b.action==='publish'||b.action==='archive'){
  if(!Array.isArray(b.ids)||b.ids.length<1||b.ids.length>50||b.ids.some(id=>typeof id!=='string'||id.length>100)||new Set(b.ids).size!==b.ids.length)throw new HttpError(400,'Select between 1 and 50 unique photographs.');
  const ids=b.ids as string[],placeholders=ids.map(()=>'?').join(',');const found=await db().prepare('SELECT COUNT(*) AS n FROM photos WHERE id IN ('+placeholders+')').bind(...ids).first<{n:number}>();if(found?.n!==ids.length)throw new HttpError(404,'One of these photographs no longer exists.');const result=await db().prepare('UPDATE photos SET published=? WHERE id IN ('+placeholders+')').bind(b.action==='publish'?1:0,...ids).run();return json({changed:result.meta.changes});
 }
 if(b.action==='sync'){
  if(typeof b.id!=='string')throw new HttpError(400,'Choose an order.');await limitAction(u.userId,'studio-order-sync',8);const order=await db().prepare('SELECT * FROM orders WHERE id=?').bind(b.id).first<Order>();if(!order)throw new HttpError(404,'Order not found.');if(order.stripe_session_id&&['pending','paid'].includes(order.status))await settle(await stripeRequest('checkout/sessions/'+encodeURIComponent(order.stripe_session_id)));return json({saved:true});
 }
 throw new HttpError(400,'Choose a supported action.');
}catch(e){return fail(e)}}
export async function DELETE(request:Request){try{checkOrigin(request);const u=await identity(true);await limitAction(u.userId,'studio-delete',10);const b=await readJson(request);if(typeof b.id!=='string'||b.confirm!=='DELETE')throw new HttpError(400,'Confirm the photograph to delete.');const photo=await db().prepare('SELECT original_key,preview_key,published FROM photos WHERE id=?').bind(b.id).first<{original_key:string;preview_key:string;published:number}>();if(!photo)throw new HttpError(404,'Photograph not found.');if(photo.published)throw new HttpError(409,'Archive the photograph before deleting it.');const result=await db().prepare('DELETE FROM photos WHERE id=? AND published=0 AND NOT EXISTS (SELECT 1 FROM orders WHERE photo_id=photos.id)').bind(b.id).run();if(!result.meta.changes)throw new HttpError(409,'This photograph has order records and must be retained. You can keep it archived.');await db().prepare('DELETE FROM bookmarks WHERE photo_id=?').bind(b.id).run();try{await bucket().delete([photo.original_key,photo.preview_key])}catch{console.error('Private photo asset cleanup needs retry',b.id)}return json({deleted:true});}catch(e){return fail(e)}}
