import {identity,readJson,checkOrigin,db,bucket,json,fail,HttpError,limitAction,photoColumns,mapPhoto} from '@/lib/server';
import {photoInput,detectedImage,safeFilename} from '@/lib/validation';
export async function GET(){try{await identity(true);const {results}=await db().prepare(`SELECT ${photoColumns} FROM photos ORDER BY created_at DESC LIMIT 200`).all();return json({photos:results.map(mapPhoto)})}catch(e){return fail(e)}}
export async function POST(request:Request){let keys:string[]=[];try{checkOrigin(request);const user=await identity(true);await limitAction(user.userId,'upload',6);if(Number(request.headers.get('content-length'))>43*1024*1024)throw new HttpError(413,'Please choose a photo under 40 MB.');
const form=await request.formData();const original=form.get('original'),preview=form.get('preview');if(!(original instanceof File)||!(preview instanceof File))throw new HttpError(400,'Choose an original photograph and its preview.');if(!original.size||original.size>40*1024*1024||!preview.size||preview.size>2*1024*1024)throw new HttpError(413,'Originals must be under 40 MB and previews under 2 MB.');
let raw;try{raw=JSON.parse(String(form.get('metadata')))}catch{throw new HttpError(400,'Photo details are not valid.')}const parsed=photoInput.safeParse(raw);if(!parsed.success)throw new HttpError(400,parsed.error.issues[0]?.message||'Check the photo details.');const p=parsed.data;
const type=detectedImage(new Uint8Array(await original.slice(0,16).arrayBuffer()));const previewType=detectedImage(new Uint8Array(await preview.slice(0,16).arrayBuffer()));if(!type||previewType!=='image/jpeg')throw new HttpError(415,'Use a JPEG, PNG or WebP original. The preview must be JPEG.');
const id=crypto.randomUUID();const slug=p.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'photograph';const now=new Date().toISOString();const ok='originals/'+id,pk='previews/'+id;keys=[ok,pk];await bucket().put(ok,original.stream(),{httpMetadata:{contentType:type}});await bucket().put(pk,preview.stream(),{httpMetadata:{contentType:'image/jpeg'}});
await db().prepare('INSERT INTO photos (id,slug,title,caption,alt,category,location,camera,lens,settings,created_at,price_cents,published,original_key,preview_key,original_name,original_type,original_size,width,height,rights_confirmed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,slug+'-'+id.slice(0,8),p.title,p.caption,p.alt,p.category,p.location,p.camera,p.lens,p.settings,now,p.price_cents,p.published,ok,pk,safeFilename(original.name),type,original.size,p.width,p.height,now).run();keys=[];return json({id,message:p.published?'Photograph published.':'Draft saved.'},201)}catch(e){if(keys.length){try{await bucket().delete(keys)}catch{console.error('Upload cleanup needs retry')}}return fail(e)}}
export async function PATCH(request:Request){try{checkOrigin(request);await identity(true);const body=await readJson(request) as Record<string,unknown>;if(typeof body.id!=='string')throw new HttpError(400,'Photo not specified.');const old=await db().prepare('SELECT * FROM photos WHERE id=?').bind(body.id).first();if(!old)throw new HttpError(404,'Photo not found.');const parsed=photoInput.safeParse({...old,...body,rights:true});if(!parsed.success)throw new HttpError(400,'Check the photo details.');const p=parsed.data;await db().prepare('UPDATE photos SET title=?,caption=?,alt=?,category=?,location=?,camera=?,lens=?,settings=?,price_cents=?,published=? WHERE id=?').bind(p.title,p.caption,p.alt,p.category,p.location,p.camera,p.lens,p.settings,p.price_cents,p.published,body.id).run();return json({saved:true})}catch(e){return fail(e)}}
