import {requireChatGPTUser} from '@/app/chatgpt-auth';
import {db,isOwner,mapPhoto,photoColumns} from '@/lib/server';
import {Dashboard} from '@/components/dashboard';
import {AccountForm} from '@/components/account-form';
import Link from 'next/link';
export const dynamic='force-dynamic';
export const metadata={title:'My collection',robots:{index:false,follow:false}};
export default async function DashboardPage({searchParams}:{searchParams:Promise<{order?:string;cancelled?:string;tab?:string}>}){const query=await searchParams;return <DashboardContent query={query}/>}
async function DashboardContent({query}:{query:{order?:string;cancelled?:string;tab?:string}}){const u=await requireChatGPTUser('/dashboard');const profile=await db().prepare('SELECT name FROM profiles WHERE user_id=?').bind(u.userId).first<{name:string}>();if(!profile)return <main id="main" className="page content-page"><div style={{maxWidth:550,margin:'50px auto'}}><AccountForm signedIn/>{isOwner(u)&&<p style={{textAlign:'center'}}><Link className="button secondary" href="/studio">Open photographer studio</Link></p>}</div></main>;
const [orders,presets,bookmarks,customOrders]=await Promise.all([db().prepare('SELECT id,photo_title,photo_id,amount,status,created_at,downloaded_at,receipt_sent_at FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(u.userId).all(),db().prepare('SELECT id,name,created_at FROM presets WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(u.userId).all(),db().prepare(`SELECT ${photoColumns.split(',').map(c=>'p.'+c).join(',')} FROM photos p JOIN bookmarks b ON p.id=b.photo_id WHERE b.user_id=? AND p.published=1 ORDER BY b.created_at DESC LIMIT 100`).bind(u.userId).all(),db().prepare('SELECT * FROM custom_orders WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(u.userId).all()]);
return <main id="main" className="page content-page"><header className="page-heading"><div><p className="eyebrow">Your collector dashboard</p><h1>My <em>collection.</em></h1><p>Welcome, {profile.name}. A home for your originals, favourite frames and shooting notes.</p></div>{isOwner(u)&&<Link className="button" href="/studio">Photographer studio</Link>}</header>{query.cancelled&&<p className="notice">Checkout was closed. If you completed a payment separately, use “Check payment” on that order.</p>}<Dashboard initialTab={query.tab} customOrders={customOrders.results as never} orders={orders.results as never} presets={presets.results as never} bookmarks={bookmarks.results.map(mapPhoto)} paymentOrder={query.order}/></main>}
